import Bool;
import Nat;
import LT;
import Acc;
import SizedList;
import List;
import Measured;
import Partition;
import natLessOrEqual;
import quickSortAcc;
import accessibleSucc;
import natAccessible;
import partition;
import quickSort;

bool_type := Bool;
nat_type := Nat;
lt_family := LT;
acc_family := Acc Nat LT;
sized_family := SizedList Nat;
measured_type := Measured Nat;
partition_type := Partition Nat Nat.zero;
list_type := List Nat;
sort_acc := quickSortAcc Nat &natLessOrEqual;
natural_access := natAccessible;
successor_access := accessibleSucc;
partition_nat := partition Nat &natLessOrEqual;
sort := \xs : List Nat => quickSort Nat &natLessOrEqual xs;
count := \n : Nat => n @zero => #0 @succ k => #int_add #1 *k;
length := \xs : List Nat => xs @nil => #0 @cons head tail => #int_add #1 *tail;
first := \xs : List Nat => xs @nil => #0 @cons head tail => count head;
empty := (List Nat).nil;
singleton := (List Nat).cons (Nat.succ Nat.zero) empty;
reference := { #print (#int_to_text (length (sort empty))); #print #",";
	#print (#int_to_text (length (sort singleton))); #print #",";
	#print (#int_to_text (first (sort singleton))); };
