#ifndef A_PROGRAM_PROTOTYPE_FRONTEND_TYPING_SOLUTION_DOMAIN_H
#define A_PROGRAM_PROTOTYPE_FRONTEND_TYPING_SOLUTION_DOMAIN_H

/* Layer T instrumentation domains. These values classify static-semantics
 * solutions and must never enter a Core Term or a Core canonical key. */
enum prototype_compile_solution_domain {
	PROTOTYPE_COMPILE_SOLUTION_CLASSIFIER = 0,
	PROTOTYPE_COMPILE_SOLUTION_MOTIVE,
	PROTOTYPE_COMPILE_SOLUTION_EFFECT,
	PROTOTYPE_COMPILE_SOLUTION_USAGE,
	PROTOTYPE_COMPILE_SOLUTION_CONTEXT,
	PROTOTYPE_COMPILE_SOLUTION_COMPUTATION,
	PROTOTYPE_COMPILE_SOLUTION_DOMAIN_COUNT
};

#endif
