add := \x : #Int32 => \y : #Int32 => #int_add x y;
sub := \x : #Int32 => \y : #Int32 => #int_sub x y;
mul := \x : #Int32 => \y : #Int32 => #int_mul x y;
neg := \x : #Int32 => #int_neg x;
add64 := \x : #Int64 => \y : #Int64 => #int64_add x y;
sub64 := \x : #Int64 => \y : #Int64 => #int64_sub x y;
mul64 := \x : #Int64 => \y : #Int64 => #int64_mul x y;
neg64 := \x : #Int64 => #int64_neg x;
identity := \x : #Int32 => x;
ignore := \x : #Int32 => #42;
composed := \x : #Int32 => \y : #Int32 => { a := add x y; b := sub x y; mul a b; };
nested := \x : #Int32 => \y : #Int32 => mul (add x y) (sub x y);
sequence := \x : #Int32 => { y := add x #1; z := mul y y; z; };
captured := \x : #Int32 => (\y : #Int32 => add x y) #7;
constant := #-2147483648;
computed := add #20 #22;
effect := \x : #Int32 => { #print #"effect"; x; };
thunk_arg := \x : #Int32 => &{ x; };
text := \x : #Int32 => #int_to_text x;
