--- a/Makefile
+++ b/Makefile
@@ -21,6 +21,7 @@
 SOURCES += $(ROOT)function_graph.c $(ROOT)host.c $(ROOT)execution.c
 SOURCES += $(ROOT)evidence_function.c $(ROOT)evidence_cbpv.c $(ROOT)evidence_identity.c
 SOURCES += $(ROOT)scope.c $(ROOT)evidence_scope.c $(ROOT)typed_query.c
+SOURCES += $(ROOT)subscription.c
 WITNESS_SOURCE := $(ROOT)function_witness.c
 SYNTHESIS_SOURCES := $(ROOT)synthesis.c $(ROOT)synthesis_work.c $(ROOT)synthesis_effect.c $(ROOT)synthesis_handler.c $(ROOT)synthesis_operation.c $(ROOT)synthesis_cbpv.c $(ROOT)synthesis_function.c $(ROOT)synthesis_context.c $(ROOT)synthesis_iadt.c $(ROOT)synthesis_identity.c
 SYNTHESIS_SOURCES += $(ROOT)synthesis_conversion.c $(ROOT)synthesis_derivation.c $(ROOT)synthesis_binding.c
