format := #int_to_text;
apply := \f : #Int -> #Text => \x : #Int => f x;
main := format (#int_add #20 #22);
expected := { #"42"; };
minimum := format #-2147483648;
minimumExpected := { #"-2147483648"; };
maximum := format #2147483647;
maximumExpected := { #"2147483647"; };
zero := format #0;
zeroExpected := { #"0"; };
wrapped := format (#int_add #2147483647 #1);
higher := apply &format #42;
partial := apply &format;
partialMain := partial #42;
raw := #print main;
handled := raw @#print req k => k req @#return x => x;
Box := \A : @ => @{ mk : A -> *; };
TextBox := Box #Text;
boxed := TextBox.mk main;
unboxed := boxed @mk x => x;
