#include "parse.h"
#include <stdio.h>

// --- Bison/Flex API Forward Declarations ---

// Scanner type (opaque pointer to lexer state)
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/**
 * @brief Parser function generated by Bison
 * @param scanner Reentrant lexer scanner
 * @param state Parse state containing symbols, arena, etc.
 */
int yyparse(yyscan_t scanner, struct parse_state* state);

/**
 * @brief Initialize reentrant lexer (generated by Flex)
 * @param extra_data User data to attach to scanner (parse_state)
 * @param scanner Output parameter for scanner handle
 */
int yylex_init_extra(void* extra_data, yyscan_t* scanner);

/**
 * @brief Destroy reentrant lexer (generated by Flex)
 */
int yylex_destroy(yyscan_t scanner);

/**
 * @brief Set input file for scanner (generated by Flex)
 */
void yyset_in(FILE* in_str, yyscan_t scanner);


/**
 * @brief Top-level function for parsing, called from main
 * @note Now fully reentrant and thread-safe
 */
int parse_file(const char* path, struct parse_state* state) {
    if (!path || !state) {
        return -1;
    }

    FILE* f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "Error: cannot open file '%s'\n", path);
        return -1;
    }

    // Initialize reentrant scanner with parse_state as extra data
    yyscan_t scanner;
    if (yylex_init_extra(state, &scanner) != 0) {
        fprintf(stderr, "Error: failed to initialize scanner\n");
        fclose(f);
        return -1;
    }

    // Set input file for scanner
    yyset_in(f, scanner);

    // Invoke the parser (now passing scanner explicitly)
    int parse_result = yyparse(scanner, state);

    // Cleanup
    yylex_destroy(scanner);
    fclose(f);

    if (parse_result != 0 || state->error_count > 0) {
        return -1;
    }

    return 0;
}
