// Concrete computational equalities, not universal tree theorems.
Nat := @{zero:*; succ:*->*;};
Bool := @{true:*; false:*;};
Tree := @{leaf:*; node:*->*->*;};
Eq := \A:@ => @\left:A => @\right:A => {refl:(x:A)->* x x;};
and := \a:Bool => \b:Bool => a @true => b @false => Bool.false;
full := \n:Nat => n @zero => Tree.leaf @succ p => Tree.node *p *p;
full :: Nat->Tree;
mirror := \t:Tree => t @leaf => Tree.leaf @node l r => Tree.node *r *l;
mirror :: Tree->Tree;
alltrue := \t:Tree => t @leaf => Bool.true @node l r => and *l *r;
alltrue :: Tree->Bool;
n0 := Nat.zero;
n1 := Nat.succ n0;
n2 := Nat.succ n1;
n3 := Nat.succ n2;
n4 := Nat.succ n3;
n5 := Nat.succ n4;
n6 := Nat.succ n5;
n7 := Nat.succ n6;
n8 := Nat.succ n7;
n9 := Nat.succ n8;
n10 := Nat.succ n9;
n11 := Nat.succ n10;
n12 := Nat.succ n11;
n13 := Nat.succ n12;
ft0 := (Eq Bool).refl Bool.true;
ft0 :: Eq Bool (alltrue (full n7)) Bool.true;
mt0 := (Eq Tree).refl (full n6);
mt0 :: Eq Tree (mirror (full n6)) (full n6);
ft1 := (Eq Bool).refl Bool.true;
ft1 :: Eq Bool (alltrue (full n12)) Bool.true;
mt1 := (Eq Tree).refl (full n9);
mt1 :: Eq Tree (mirror (full n9)) (full n9);
ft2 := (Eq Bool).refl Bool.true;
ft2 :: Eq Bool (alltrue (full n11)) Bool.true;
mt2 := (Eq Tree).refl (full n7);
mt2 :: Eq Tree (mirror (full n7)) (full n7);
ft3 := (Eq Bool).refl Bool.true;
ft3 :: Eq Bool (alltrue (full n10)) Bool.true;
mt3 := (Eq Tree).refl (full n10);
mt3 :: Eq Tree (mirror (full n10)) (full n10);
ft4 := (Eq Bool).refl Bool.true;
ft4 :: Eq Bool (alltrue (full n9)) Bool.true;
mt4 := (Eq Tree).refl (full n8);
mt4 :: Eq Tree (mirror (full n8)) (full n8);
ft5 := (Eq Bool).refl Bool.true;
ft5 :: Eq Bool (alltrue (full n8)) Bool.true;
mt5 := (Eq Tree).refl (full n6);
mt5 :: Eq Tree (mirror (full n6)) (full n6);
ft6 := (Eq Bool).refl Bool.true;
ft6 :: Eq Bool (alltrue (full n7)) Bool.true;
mt6 := (Eq Tree).refl (full n9);
mt6 :: Eq Tree (mirror (full n9)) (full n9);
ft7 := (Eq Bool).refl Bool.true;
ft7 :: Eq Bool (alltrue (full n12)) Bool.true;
mt7 := (Eq Tree).refl (full n7);
mt7 :: Eq Tree (mirror (full n7)) (full n7);
ft8 := (Eq Bool).refl Bool.true;
ft8 :: Eq Bool (alltrue (full n11)) Bool.true;
mt8 := (Eq Tree).refl (full n10);
mt8 :: Eq Tree (mirror (full n10)) (full n10);
ft9 := (Eq Bool).refl Bool.true;
ft9 :: Eq Bool (alltrue (full n10)) Bool.true;
mt9 := (Eq Tree).refl (full n8);
mt9 :: Eq Tree (mirror (full n8)) (full n8);
ft10 := (Eq Bool).refl Bool.true;
ft10 :: Eq Bool (alltrue (full n9)) Bool.true;
mt10 := (Eq Tree).refl (full n6);
mt10 :: Eq Tree (mirror (full n6)) (full n6);
ft11 := (Eq Bool).refl Bool.true;
ft11 :: Eq Bool (alltrue (full n8)) Bool.true;
mt11 := (Eq Tree).refl (full n9);
mt11 :: Eq Tree (mirror (full n9)) (full n9);
ft12 := (Eq Bool).refl Bool.true;
ft12 :: Eq Bool (alltrue (full n7)) Bool.true;
mt12 := (Eq Tree).refl (full n7);
mt12 :: Eq Tree (mirror (full n7)) (full n7);
ft13 := (Eq Bool).refl Bool.true;
ft13 :: Eq Bool (alltrue (full n12)) Bool.true;
mt13 := (Eq Tree).refl (full n10);
mt13 :: Eq Tree (mirror (full n10)) (full n10);
ft14 := (Eq Bool).refl Bool.true;
ft14 :: Eq Bool (alltrue (full n11)) Bool.true;
mt14 := (Eq Tree).refl (full n8);
mt14 :: Eq Tree (mirror (full n8)) (full n8);
ft15 := (Eq Bool).refl Bool.true;
ft15 :: Eq Bool (alltrue (full n10)) Bool.true;
mt15 := (Eq Tree).refl (full n6);
mt15 :: Eq Tree (mirror (full n6)) (full n6);
ft16 := (Eq Bool).refl Bool.true;
ft16 :: Eq Bool (alltrue (full n9)) Bool.true;
mt16 := (Eq Tree).refl (full n9);
mt16 :: Eq Tree (mirror (full n9)) (full n9);
ft17 := (Eq Bool).refl Bool.true;
ft17 :: Eq Bool (alltrue (full n8)) Bool.true;
mt17 := (Eq Tree).refl (full n7);
mt17 :: Eq Tree (mirror (full n7)) (full n7);
ft18 := (Eq Bool).refl Bool.true;
ft18 :: Eq Bool (alltrue (full n7)) Bool.true;
mt18 := (Eq Tree).refl (full n10);
mt18 :: Eq Tree (mirror (full n10)) (full n10);
ft19 := (Eq Bool).refl Bool.true;
ft19 :: Eq Bool (alltrue (full n12)) Bool.true;
mt19 := (Eq Tree).refl (full n8);
mt19 :: Eq Tree (mirror (full n8)) (full n8);
ft20 := (Eq Bool).refl Bool.true;
ft20 :: Eq Bool (alltrue (full n11)) Bool.true;
mt20 := (Eq Tree).refl (full n6);
mt20 :: Eq Tree (mirror (full n6)) (full n6);
ft21 := (Eq Bool).refl Bool.true;
ft21 :: Eq Bool (alltrue (full n10)) Bool.true;
mt21 := (Eq Tree).refl (full n9);
mt21 :: Eq Tree (mirror (full n9)) (full n9);
ft22 := (Eq Bool).refl Bool.true;
ft22 :: Eq Bool (alltrue (full n9)) Bool.true;
mt22 := (Eq Tree).refl (full n7);
mt22 :: Eq Tree (mirror (full n7)) (full n7);
ft23 := (Eq Bool).refl Bool.true;
ft23 :: Eq Bool (alltrue (full n8)) Bool.true;
mt23 := (Eq Tree).refl (full n10);
mt23 :: Eq Tree (mirror (full n10)) (full n10);
ft24 := (Eq Bool).refl Bool.true;
ft24 :: Eq Bool (alltrue (full n7)) Bool.true;
mt24 := (Eq Tree).refl (full n8);
mt24 :: Eq Tree (mirror (full n8)) (full n8);
ft25 := (Eq Bool).refl Bool.true;
ft25 :: Eq Bool (alltrue (full n12)) Bool.true;
mt25 := (Eq Tree).refl (full n6);
mt25 :: Eq Tree (mirror (full n6)) (full n6);
ft26 := (Eq Bool).refl Bool.true;
ft26 :: Eq Bool (alltrue (full n11)) Bool.true;
mt26 := (Eq Tree).refl (full n9);
mt26 :: Eq Tree (mirror (full n9)) (full n9);
ft27 := (Eq Bool).refl Bool.true;
ft27 :: Eq Bool (alltrue (full n10)) Bool.true;
mt27 := (Eq Tree).refl (full n7);
mt27 :: Eq Tree (mirror (full n7)) (full n7);
ft28 := (Eq Bool).refl Bool.true;
ft28 :: Eq Bool (alltrue (full n9)) Bool.true;
mt28 := (Eq Tree).refl (full n10);
mt28 :: Eq Tree (mirror (full n10)) (full n10);
ft29 := (Eq Bool).refl Bool.true;
ft29 :: Eq Bool (alltrue (full n8)) Bool.true;
mt29 := (Eq Tree).refl (full n8);
mt29 :: Eq Tree (mirror (full n8)) (full n8);
ft30 := (Eq Bool).refl Bool.true;
ft30 :: Eq Bool (alltrue (full n7)) Bool.true;
mt30 := (Eq Tree).refl (full n6);
mt30 :: Eq Tree (mirror (full n6)) (full n6);
ft31 := (Eq Bool).refl Bool.true;
ft31 :: Eq Bool (alltrue (full n12)) Bool.true;
mt31 := (Eq Tree).refl (full n9);
mt31 :: Eq Tree (mirror (full n9)) (full n9);
ft32 := (Eq Bool).refl Bool.true;
ft32 :: Eq Bool (alltrue (full n11)) Bool.true;
mt32 := (Eq Tree).refl (full n7);
mt32 :: Eq Tree (mirror (full n7)) (full n7);
ft33 := (Eq Bool).refl Bool.true;
ft33 :: Eq Bool (alltrue (full n10)) Bool.true;
mt33 := (Eq Tree).refl (full n10);
mt33 :: Eq Tree (mirror (full n10)) (full n10);
ft34 := (Eq Bool).refl Bool.true;
ft34 :: Eq Bool (alltrue (full n9)) Bool.true;
mt34 := (Eq Tree).refl (full n8);
mt34 :: Eq Tree (mirror (full n8)) (full n8);
ft35 := (Eq Bool).refl Bool.true;
ft35 :: Eq Bool (alltrue (full n8)) Bool.true;
mt35 := (Eq Tree).refl (full n6);
mt35 :: Eq Tree (mirror (full n6)) (full n6);
ft36 := (Eq Bool).refl Bool.true;
ft36 :: Eq Bool (alltrue (full n7)) Bool.true;
mt36 := (Eq Tree).refl (full n9);
mt36 :: Eq Tree (mirror (full n9)) (full n9);
ft37 := (Eq Bool).refl Bool.true;
ft37 :: Eq Bool (alltrue (full n12)) Bool.true;
mt37 := (Eq Tree).refl (full n7);
mt37 :: Eq Tree (mirror (full n7)) (full n7);
ft38 := (Eq Bool).refl Bool.true;
ft38 :: Eq Bool (alltrue (full n11)) Bool.true;
mt38 := (Eq Tree).refl (full n10);
mt38 :: Eq Tree (mirror (full n10)) (full n10);
ft39 := (Eq Bool).refl Bool.true;
ft39 :: Eq Bool (alltrue (full n10)) Bool.true;
mt39 := (Eq Tree).refl (full n8);
mt39 :: Eq Tree (mirror (full n8)) (full n8);
ft40 := (Eq Bool).refl Bool.true;
ft40 :: Eq Bool (alltrue (full n9)) Bool.true;
mt40 := (Eq Tree).refl (full n6);
mt40 :: Eq Tree (mirror (full n6)) (full n6);
ft41 := (Eq Bool).refl Bool.true;
ft41 :: Eq Bool (alltrue (full n8)) Bool.true;
mt41 := (Eq Tree).refl (full n9);
mt41 :: Eq Tree (mirror (full n9)) (full n9);
ft42 := (Eq Bool).refl Bool.true;
ft42 :: Eq Bool (alltrue (full n7)) Bool.true;
mt42 := (Eq Tree).refl (full n7);
mt42 :: Eq Tree (mirror (full n7)) (full n7);
ft43 := (Eq Bool).refl Bool.true;
ft43 :: Eq Bool (alltrue (full n12)) Bool.true;
mt43 := (Eq Tree).refl (full n10);
mt43 :: Eq Tree (mirror (full n10)) (full n10);
ft44 := (Eq Bool).refl Bool.true;
ft44 :: Eq Bool (alltrue (full n11)) Bool.true;
mt44 := (Eq Tree).refl (full n8);
mt44 :: Eq Tree (mirror (full n8)) (full n8);
ft45 := (Eq Bool).refl Bool.true;
ft45 :: Eq Bool (alltrue (full n10)) Bool.true;
mt45 := (Eq Tree).refl (full n6);
mt45 :: Eq Tree (mirror (full n6)) (full n6);
ft46 := (Eq Bool).refl Bool.true;
ft46 :: Eq Bool (alltrue (full n9)) Bool.true;
mt46 := (Eq Tree).refl (full n9);
mt46 :: Eq Tree (mirror (full n9)) (full n9);
ft47 := (Eq Bool).refl Bool.true;
ft47 :: Eq Bool (alltrue (full n8)) Bool.true;
mt47 := (Eq Tree).refl (full n7);
mt47 :: Eq Tree (mirror (full n7)) (full n7);
ft48 := (Eq Bool).refl Bool.true;
ft48 :: Eq Bool (alltrue (full n7)) Bool.true;
mt48 := (Eq Tree).refl (full n10);
mt48 :: Eq Tree (mirror (full n10)) (full n10);
ft49 := (Eq Bool).refl Bool.true;
ft49 :: Eq Bool (alltrue (full n12)) Bool.true;
mt49 := (Eq Tree).refl (full n8);
mt49 :: Eq Tree (mirror (full n8)) (full n8);
ft50 := (Eq Bool).refl Bool.true;
ft50 :: Eq Bool (alltrue (full n11)) Bool.true;
mt50 := (Eq Tree).refl (full n6);
mt50 :: Eq Tree (mirror (full n6)) (full n6);
ft51 := (Eq Bool).refl Bool.true;
ft51 :: Eq Bool (alltrue (full n10)) Bool.true;
mt51 := (Eq Tree).refl (full n9);
mt51 :: Eq Tree (mirror (full n9)) (full n9);
ft52 := (Eq Bool).refl Bool.true;
ft52 :: Eq Bool (alltrue (full n9)) Bool.true;
mt52 := (Eq Tree).refl (full n7);
mt52 :: Eq Tree (mirror (full n7)) (full n7);
ft53 := (Eq Bool).refl Bool.true;
ft53 :: Eq Bool (alltrue (full n8)) Bool.true;
mt53 := (Eq Tree).refl (full n10);
mt53 :: Eq Tree (mirror (full n10)) (full n10);
ft54 := (Eq Bool).refl Bool.true;
ft54 :: Eq Bool (alltrue (full n7)) Bool.true;
mt54 := (Eq Tree).refl (full n8);
mt54 :: Eq Tree (mirror (full n8)) (full n8);
ft55 := (Eq Bool).refl Bool.true;
ft55 :: Eq Bool (alltrue (full n12)) Bool.true;
mt55 := (Eq Tree).refl (full n6);
mt55 :: Eq Tree (mirror (full n6)) (full n6);
ft56 := (Eq Bool).refl Bool.true;
ft56 :: Eq Bool (alltrue (full n11)) Bool.true;
mt56 := (Eq Tree).refl (full n9);
mt56 :: Eq Tree (mirror (full n9)) (full n9);
ft57 := (Eq Bool).refl Bool.true;
ft57 :: Eq Bool (alltrue (full n10)) Bool.true;
mt57 := (Eq Tree).refl (full n7);
mt57 :: Eq Tree (mirror (full n7)) (full n7);
ft58 := (Eq Bool).refl Bool.true;
ft58 :: Eq Bool (alltrue (full n9)) Bool.true;
mt58 := (Eq Tree).refl (full n10);
mt58 :: Eq Tree (mirror (full n10)) (full n10);
ft59 := (Eq Bool).refl Bool.true;
ft59 :: Eq Bool (alltrue (full n8)) Bool.true;
mt59 := (Eq Tree).refl (full n8);
mt59 :: Eq Tree (mirror (full n8)) (full n8);
ft60 := (Eq Bool).refl Bool.true;
ft60 :: Eq Bool (alltrue (full n7)) Bool.true;
mt60 := (Eq Tree).refl (full n6);
mt60 :: Eq Tree (mirror (full n6)) (full n6);
ft61 := (Eq Bool).refl Bool.true;
ft61 :: Eq Bool (alltrue (full n12)) Bool.true;
mt61 := (Eq Tree).refl (full n9);
mt61 :: Eq Tree (mirror (full n9)) (full n9);
ft62 := (Eq Bool).refl Bool.true;
ft62 :: Eq Bool (alltrue (full n11)) Bool.true;
mt62 := (Eq Tree).refl (full n7);
mt62 :: Eq Tree (mirror (full n7)) (full n7);
ft63 := (Eq Bool).refl Bool.true;
ft63 :: Eq Bool (alltrue (full n10)) Bool.true;
mt63 := (Eq Tree).refl (full n10);
mt63 :: Eq Tree (mirror (full n10)) (full n10);
ft64 := (Eq Bool).refl Bool.true;
ft64 :: Eq Bool (alltrue (full n9)) Bool.true;
mt64 := (Eq Tree).refl (full n8);
mt64 :: Eq Tree (mirror (full n8)) (full n8);
ft65 := (Eq Bool).refl Bool.true;
ft65 :: Eq Bool (alltrue (full n8)) Bool.true;
mt65 := (Eq Tree).refl (full n6);
mt65 :: Eq Tree (mirror (full n6)) (full n6);
ft66 := (Eq Bool).refl Bool.true;
ft66 :: Eq Bool (alltrue (full n7)) Bool.true;
mt66 := (Eq Tree).refl (full n9);
mt66 :: Eq Tree (mirror (full n9)) (full n9);
ft67 := (Eq Bool).refl Bool.true;
ft67 :: Eq Bool (alltrue (full n12)) Bool.true;
mt67 := (Eq Tree).refl (full n7);
mt67 :: Eq Tree (mirror (full n7)) (full n7);
ft68 := (Eq Bool).refl Bool.true;
ft68 :: Eq Bool (alltrue (full n11)) Bool.true;
mt68 := (Eq Tree).refl (full n10);
mt68 :: Eq Tree (mirror (full n10)) (full n10);
ft69 := (Eq Bool).refl Bool.true;
ft69 :: Eq Bool (alltrue (full n10)) Bool.true;
mt69 := (Eq Tree).refl (full n8);
mt69 :: Eq Tree (mirror (full n8)) (full n8);
ft70 := (Eq Bool).refl Bool.true;
ft70 :: Eq Bool (alltrue (full n9)) Bool.true;
mt70 := (Eq Tree).refl (full n6);
mt70 :: Eq Tree (mirror (full n6)) (full n6);
ft71 := (Eq Bool).refl Bool.true;
ft71 :: Eq Bool (alltrue (full n8)) Bool.true;
mt71 := (Eq Tree).refl (full n9);
mt71 :: Eq Tree (mirror (full n9)) (full n9);
ft72 := (Eq Bool).refl Bool.true;
ft72 :: Eq Bool (alltrue (full n7)) Bool.true;
mt72 := (Eq Tree).refl (full n7);
mt72 :: Eq Tree (mirror (full n7)) (full n7);
ft73 := (Eq Bool).refl Bool.true;
ft73 :: Eq Bool (alltrue (full n12)) Bool.true;
mt73 := (Eq Tree).refl (full n10);
mt73 :: Eq Tree (mirror (full n10)) (full n10);
ft74 := (Eq Bool).refl Bool.true;
ft74 :: Eq Bool (alltrue (full n11)) Bool.true;
mt74 := (Eq Tree).refl (full n8);
mt74 :: Eq Tree (mirror (full n8)) (full n8);
ft75 := (Eq Bool).refl Bool.true;
ft75 :: Eq Bool (alltrue (full n10)) Bool.true;
mt75 := (Eq Tree).refl (full n6);
mt75 :: Eq Tree (mirror (full n6)) (full n6);
ft76 := (Eq Bool).refl Bool.true;
ft76 :: Eq Bool (alltrue (full n9)) Bool.true;
mt76 := (Eq Tree).refl (full n9);
mt76 :: Eq Tree (mirror (full n9)) (full n9);
ft77 := (Eq Bool).refl Bool.true;
ft77 :: Eq Bool (alltrue (full n8)) Bool.true;
mt77 := (Eq Tree).refl (full n7);
mt77 :: Eq Tree (mirror (full n7)) (full n7);
ft78 := (Eq Bool).refl Bool.true;
ft78 :: Eq Bool (alltrue (full n7)) Bool.true;
mt78 := (Eq Tree).refl (full n10);
mt78 :: Eq Tree (mirror (full n10)) (full n10);
ft79 := (Eq Bool).refl Bool.true;
ft79 :: Eq Bool (alltrue (full n12)) Bool.true;
mt79 := (Eq Tree).refl (full n8);
mt79 :: Eq Tree (mirror (full n8)) (full n8);
ft80 := (Eq Bool).refl Bool.true;
ft80 :: Eq Bool (alltrue (full n11)) Bool.true;
mt80 := (Eq Tree).refl (full n6);
mt80 :: Eq Tree (mirror (full n6)) (full n6);
ft81 := (Eq Bool).refl Bool.true;
ft81 :: Eq Bool (alltrue (full n10)) Bool.true;
mt81 := (Eq Tree).refl (full n9);
mt81 :: Eq Tree (mirror (full n9)) (full n9);
ft82 := (Eq Bool).refl Bool.true;
ft82 :: Eq Bool (alltrue (full n9)) Bool.true;
mt82 := (Eq Tree).refl (full n7);
mt82 :: Eq Tree (mirror (full n7)) (full n7);
ft83 := (Eq Bool).refl Bool.true;
ft83 :: Eq Bool (alltrue (full n8)) Bool.true;
mt83 := (Eq Tree).refl (full n10);
mt83 :: Eq Tree (mirror (full n10)) (full n10);
ft84 := (Eq Bool).refl Bool.true;
ft84 :: Eq Bool (alltrue (full n7)) Bool.true;
mt84 := (Eq Tree).refl (full n8);
mt84 :: Eq Tree (mirror (full n8)) (full n8);
ft85 := (Eq Bool).refl Bool.true;
ft85 :: Eq Bool (alltrue (full n12)) Bool.true;
mt85 := (Eq Tree).refl (full n6);
mt85 :: Eq Tree (mirror (full n6)) (full n6);
ft86 := (Eq Bool).refl Bool.true;
ft86 :: Eq Bool (alltrue (full n11)) Bool.true;
mt86 := (Eq Tree).refl (full n9);
mt86 :: Eq Tree (mirror (full n9)) (full n9);
ft87 := (Eq Bool).refl Bool.true;
ft87 :: Eq Bool (alltrue (full n10)) Bool.true;
mt87 := (Eq Tree).refl (full n7);
mt87 :: Eq Tree (mirror (full n7)) (full n7);
ft88 := (Eq Bool).refl Bool.true;
ft88 :: Eq Bool (alltrue (full n9)) Bool.true;
mt88 := (Eq Tree).refl (full n10);
mt88 :: Eq Tree (mirror (full n10)) (full n10);
ft89 := (Eq Bool).refl Bool.true;
ft89 :: Eq Bool (alltrue (full n8)) Bool.true;
mt89 := (Eq Tree).refl (full n8);
mt89 :: Eq Tree (mirror (full n8)) (full n8);
ft90 := (Eq Bool).refl Bool.true;
ft90 :: Eq Bool (alltrue (full n7)) Bool.true;
mt90 := (Eq Tree).refl (full n6);
mt90 :: Eq Tree (mirror (full n6)) (full n6);
ft91 := (Eq Bool).refl Bool.true;
ft91 :: Eq Bool (alltrue (full n12)) Bool.true;
mt91 := (Eq Tree).refl (full n9);
mt91 :: Eq Tree (mirror (full n9)) (full n9);
ft92 := (Eq Bool).refl Bool.true;
ft92 :: Eq Bool (alltrue (full n11)) Bool.true;
mt92 := (Eq Tree).refl (full n7);
mt92 :: Eq Tree (mirror (full n7)) (full n7);
ft93 := (Eq Bool).refl Bool.true;
ft93 :: Eq Bool (alltrue (full n10)) Bool.true;
mt93 := (Eq Tree).refl (full n10);
mt93 :: Eq Tree (mirror (full n10)) (full n10);
ft94 := (Eq Bool).refl Bool.true;
ft94 :: Eq Bool (alltrue (full n9)) Bool.true;
mt94 := (Eq Tree).refl (full n8);
mt94 :: Eq Tree (mirror (full n8)) (full n8);
ft95 := (Eq Bool).refl Bool.true;
ft95 :: Eq Bool (alltrue (full n8)) Bool.true;
mt95 := (Eq Tree).refl (full n6);
mt95 :: Eq Tree (mirror (full n6)) (full n6);
ft96 := (Eq Bool).refl Bool.true;
ft96 :: Eq Bool (alltrue (full n7)) Bool.true;
mt96 := (Eq Tree).refl (full n9);
mt96 :: Eq Tree (mirror (full n9)) (full n9);
ft97 := (Eq Bool).refl Bool.true;
ft97 :: Eq Bool (alltrue (full n12)) Bool.true;
mt97 := (Eq Tree).refl (full n7);
mt97 :: Eq Tree (mirror (full n7)) (full n7);
ft98 := (Eq Bool).refl Bool.true;
ft98 :: Eq Bool (alltrue (full n11)) Bool.true;
mt98 := (Eq Tree).refl (full n10);
mt98 :: Eq Tree (mirror (full n10)) (full n10);
ft99 := (Eq Bool).refl Bool.true;
ft99 :: Eq Bool (alltrue (full n10)) Bool.true;
mt99 := (Eq Tree).refl (full n8);
mt99 :: Eq Tree (mirror (full n8)) (full n8);
ft100 := (Eq Bool).refl Bool.true;
ft100 :: Eq Bool (alltrue (full n9)) Bool.true;
mt100 := (Eq Tree).refl (full n6);
mt100 :: Eq Tree (mirror (full n6)) (full n6);
ft101 := (Eq Bool).refl Bool.true;
ft101 :: Eq Bool (alltrue (full n8)) Bool.true;
mt101 := (Eq Tree).refl (full n9);
mt101 :: Eq Tree (mirror (full n9)) (full n9);
ft102 := (Eq Bool).refl Bool.true;
ft102 :: Eq Bool (alltrue (full n7)) Bool.true;
mt102 := (Eq Tree).refl (full n7);
mt102 :: Eq Tree (mirror (full n7)) (full n7);
ft103 := (Eq Bool).refl Bool.true;
ft103 :: Eq Bool (alltrue (full n12)) Bool.true;
mt103 := (Eq Tree).refl (full n10);
mt103 :: Eq Tree (mirror (full n10)) (full n10);
ft104 := (Eq Bool).refl Bool.true;
ft104 :: Eq Bool (alltrue (full n11)) Bool.true;
mt104 := (Eq Tree).refl (full n8);
mt104 :: Eq Tree (mirror (full n8)) (full n8);
ft105 := (Eq Bool).refl Bool.true;
ft105 :: Eq Bool (alltrue (full n10)) Bool.true;
mt105 := (Eq Tree).refl (full n6);
mt105 :: Eq Tree (mirror (full n6)) (full n6);
ft106 := (Eq Bool).refl Bool.true;
ft106 :: Eq Bool (alltrue (full n9)) Bool.true;
mt106 := (Eq Tree).refl (full n9);
mt106 :: Eq Tree (mirror (full n9)) (full n9);
ft107 := (Eq Bool).refl Bool.true;
ft107 :: Eq Bool (alltrue (full n8)) Bool.true;
mt107 := (Eq Tree).refl (full n7);
mt107 :: Eq Tree (mirror (full n7)) (full n7);
ft108 := (Eq Bool).refl Bool.true;
ft108 :: Eq Bool (alltrue (full n7)) Bool.true;
mt108 := (Eq Tree).refl (full n10);
mt108 :: Eq Tree (mirror (full n10)) (full n10);
ft109 := (Eq Bool).refl Bool.true;
ft109 :: Eq Bool (alltrue (full n12)) Bool.true;
mt109 := (Eq Tree).refl (full n8);
mt109 :: Eq Tree (mirror (full n8)) (full n8);
ft110 := (Eq Bool).refl Bool.true;
ft110 :: Eq Bool (alltrue (full n11)) Bool.true;
mt110 := (Eq Tree).refl (full n6);
mt110 :: Eq Tree (mirror (full n6)) (full n6);
ft111 := (Eq Bool).refl Bool.true;
ft111 :: Eq Bool (alltrue (full n10)) Bool.true;
mt111 := (Eq Tree).refl (full n9);
mt111 :: Eq Tree (mirror (full n9)) (full n9);
ft112 := (Eq Bool).refl Bool.true;
ft112 :: Eq Bool (alltrue (full n9)) Bool.true;
mt112 := (Eq Tree).refl (full n7);
mt112 :: Eq Tree (mirror (full n7)) (full n7);
ft113 := (Eq Bool).refl Bool.true;
ft113 :: Eq Bool (alltrue (full n8)) Bool.true;
mt113 := (Eq Tree).refl (full n10);
mt113 :: Eq Tree (mirror (full n10)) (full n10);
ft114 := (Eq Bool).refl Bool.true;
ft114 :: Eq Bool (alltrue (full n7)) Bool.true;
mt114 := (Eq Tree).refl (full n8);
mt114 :: Eq Tree (mirror (full n8)) (full n8);
ft115 := (Eq Bool).refl Bool.true;
ft115 :: Eq Bool (alltrue (full n12)) Bool.true;
mt115 := (Eq Tree).refl (full n6);
mt115 :: Eq Tree (mirror (full n6)) (full n6);
ft116 := (Eq Bool).refl Bool.true;
ft116 :: Eq Bool (alltrue (full n11)) Bool.true;
mt116 := (Eq Tree).refl (full n9);
mt116 :: Eq Tree (mirror (full n9)) (full n9);
ft117 := (Eq Bool).refl Bool.true;
ft117 :: Eq Bool (alltrue (full n10)) Bool.true;
mt117 := (Eq Tree).refl (full n7);
mt117 :: Eq Tree (mirror (full n7)) (full n7);
ft118 := (Eq Bool).refl Bool.true;
ft118 :: Eq Bool (alltrue (full n9)) Bool.true;
mt118 := (Eq Tree).refl (full n10);
mt118 :: Eq Tree (mirror (full n10)) (full n10);
ft119 := (Eq Bool).refl Bool.true;
ft119 :: Eq Bool (alltrue (full n8)) Bool.true;
mt119 := (Eq Tree).refl (full n8);
mt119 :: Eq Tree (mirror (full n8)) (full n8);
ft120 := (Eq Bool).refl Bool.true;
ft120 :: Eq Bool (alltrue (full n7)) Bool.true;
mt120 := (Eq Tree).refl (full n6);
mt120 :: Eq Tree (mirror (full n6)) (full n6);
ft121 := (Eq Bool).refl Bool.true;
ft121 :: Eq Bool (alltrue (full n12)) Bool.true;
mt121 := (Eq Tree).refl (full n9);
mt121 :: Eq Tree (mirror (full n9)) (full n9);
ft122 := (Eq Bool).refl Bool.true;
ft122 :: Eq Bool (alltrue (full n11)) Bool.true;
mt122 := (Eq Tree).refl (full n7);
mt122 :: Eq Tree (mirror (full n7)) (full n7);
ft123 := (Eq Bool).refl Bool.true;
ft123 :: Eq Bool (alltrue (full n10)) Bool.true;
mt123 := (Eq Tree).refl (full n10);
mt123 :: Eq Tree (mirror (full n10)) (full n10);
ft124 := (Eq Bool).refl Bool.true;
ft124 :: Eq Bool (alltrue (full n9)) Bool.true;
mt124 := (Eq Tree).refl (full n8);
mt124 :: Eq Tree (mirror (full n8)) (full n8);
ft125 := (Eq Bool).refl Bool.true;
ft125 :: Eq Bool (alltrue (full n8)) Bool.true;
mt125 := (Eq Tree).refl (full n6);
mt125 :: Eq Tree (mirror (full n6)) (full n6);
ft126 := (Eq Bool).refl Bool.true;
ft126 :: Eq Bool (alltrue (full n7)) Bool.true;
mt126 := (Eq Tree).refl (full n9);
mt126 :: Eq Tree (mirror (full n9)) (full n9);
ft127 := (Eq Bool).refl Bool.true;
ft127 :: Eq Bool (alltrue (full n12)) Bool.true;
mt127 := (Eq Tree).refl (full n7);
mt127 :: Eq Tree (mirror (full n7)) (full n7);
ft128 := (Eq Bool).refl Bool.true;
ft128 :: Eq Bool (alltrue (full n11)) Bool.true;
mt128 := (Eq Tree).refl (full n10);
mt128 :: Eq Tree (mirror (full n10)) (full n10);
ft129 := (Eq Bool).refl Bool.true;
ft129 :: Eq Bool (alltrue (full n10)) Bool.true;
mt129 := (Eq Tree).refl (full n8);
mt129 :: Eq Tree (mirror (full n8)) (full n8);
ft130 := (Eq Bool).refl Bool.true;
ft130 :: Eq Bool (alltrue (full n9)) Bool.true;
mt130 := (Eq Tree).refl (full n6);
mt130 :: Eq Tree (mirror (full n6)) (full n6);
ft131 := (Eq Bool).refl Bool.true;
ft131 :: Eq Bool (alltrue (full n8)) Bool.true;
mt131 := (Eq Tree).refl (full n9);
mt131 :: Eq Tree (mirror (full n9)) (full n9);
ft132 := (Eq Bool).refl Bool.true;
ft132 :: Eq Bool (alltrue (full n7)) Bool.true;
mt132 := (Eq Tree).refl (full n7);
mt132 :: Eq Tree (mirror (full n7)) (full n7);
ft133 := (Eq Bool).refl Bool.true;
ft133 :: Eq Bool (alltrue (full n12)) Bool.true;
mt133 := (Eq Tree).refl (full n10);
mt133 :: Eq Tree (mirror (full n10)) (full n10);
ft134 := (Eq Bool).refl Bool.true;
ft134 :: Eq Bool (alltrue (full n11)) Bool.true;
mt134 := (Eq Tree).refl (full n8);
mt134 :: Eq Tree (mirror (full n8)) (full n8);
ft135 := (Eq Bool).refl Bool.true;
ft135 :: Eq Bool (alltrue (full n10)) Bool.true;
mt135 := (Eq Tree).refl (full n6);
mt135 :: Eq Tree (mirror (full n6)) (full n6);
ft136 := (Eq Bool).refl Bool.true;
ft136 :: Eq Bool (alltrue (full n9)) Bool.true;
mt136 := (Eq Tree).refl (full n9);
mt136 :: Eq Tree (mirror (full n9)) (full n9);
ft137 := (Eq Bool).refl Bool.true;
ft137 :: Eq Bool (alltrue (full n8)) Bool.true;
mt137 := (Eq Tree).refl (full n7);
mt137 :: Eq Tree (mirror (full n7)) (full n7);
ft138 := (Eq Bool).refl Bool.true;
ft138 :: Eq Bool (alltrue (full n7)) Bool.true;
mt138 := (Eq Tree).refl (full n10);
mt138 :: Eq Tree (mirror (full n10)) (full n10);
ft139 := (Eq Bool).refl Bool.true;
ft139 :: Eq Bool (alltrue (full n12)) Bool.true;
mt139 := (Eq Tree).refl (full n8);
mt139 :: Eq Tree (mirror (full n8)) (full n8);
ft140 := (Eq Bool).refl Bool.true;
ft140 :: Eq Bool (alltrue (full n11)) Bool.true;
mt140 := (Eq Tree).refl (full n6);
mt140 :: Eq Tree (mirror (full n6)) (full n6);
ft141 := (Eq Bool).refl Bool.true;
ft141 :: Eq Bool (alltrue (full n10)) Bool.true;
mt141 := (Eq Tree).refl (full n9);
mt141 :: Eq Tree (mirror (full n9)) (full n9);
ft142 := (Eq Bool).refl Bool.true;
ft142 :: Eq Bool (alltrue (full n9)) Bool.true;
mt142 := (Eq Tree).refl (full n7);
mt142 :: Eq Tree (mirror (full n7)) (full n7);
ft143 := (Eq Bool).refl Bool.true;
ft143 :: Eq Bool (alltrue (full n8)) Bool.true;
mt143 := (Eq Tree).refl (full n10);
mt143 :: Eq Tree (mirror (full n10)) (full n10);
ft144 := (Eq Bool).refl Bool.true;
ft144 :: Eq Bool (alltrue (full n7)) Bool.true;
mt144 := (Eq Tree).refl (full n8);
mt144 :: Eq Tree (mirror (full n8)) (full n8);
ft145 := (Eq Bool).refl Bool.true;
ft145 :: Eq Bool (alltrue (full n12)) Bool.true;
mt145 := (Eq Tree).refl (full n6);
mt145 :: Eq Tree (mirror (full n6)) (full n6);
ft146 := (Eq Bool).refl Bool.true;
ft146 :: Eq Bool (alltrue (full n11)) Bool.true;
mt146 := (Eq Tree).refl (full n9);
mt146 :: Eq Tree (mirror (full n9)) (full n9);
ft147 := (Eq Bool).refl Bool.true;
ft147 :: Eq Bool (alltrue (full n10)) Bool.true;
mt147 := (Eq Tree).refl (full n7);
mt147 :: Eq Tree (mirror (full n7)) (full n7);
ft148 := (Eq Bool).refl Bool.true;
ft148 :: Eq Bool (alltrue (full n9)) Bool.true;
mt148 := (Eq Tree).refl (full n10);
mt148 :: Eq Tree (mirror (full n10)) (full n10);
ft149 := (Eq Bool).refl Bool.true;
ft149 :: Eq Bool (alltrue (full n8)) Bool.true;
mt149 := (Eq Tree).refl (full n8);
mt149 :: Eq Tree (mirror (full n8)) (full n8);
ft150 := (Eq Bool).refl Bool.true;
ft150 :: Eq Bool (alltrue (full n7)) Bool.true;
mt150 := (Eq Tree).refl (full n6);
mt150 :: Eq Tree (mirror (full n6)) (full n6);
ft151 := (Eq Bool).refl Bool.true;
ft151 :: Eq Bool (alltrue (full n12)) Bool.true;
mt151 := (Eq Tree).refl (full n9);
mt151 :: Eq Tree (mirror (full n9)) (full n9);
ft152 := (Eq Bool).refl Bool.true;
ft152 :: Eq Bool (alltrue (full n11)) Bool.true;
mt152 := (Eq Tree).refl (full n7);
mt152 :: Eq Tree (mirror (full n7)) (full n7);
ft153 := (Eq Bool).refl Bool.true;
ft153 :: Eq Bool (alltrue (full n10)) Bool.true;
mt153 := (Eq Tree).refl (full n10);
mt153 :: Eq Tree (mirror (full n10)) (full n10);
ft154 := (Eq Bool).refl Bool.true;
ft154 :: Eq Bool (alltrue (full n9)) Bool.true;
mt154 := (Eq Tree).refl (full n8);
mt154 :: Eq Tree (mirror (full n8)) (full n8);
ft155 := (Eq Bool).refl Bool.true;
ft155 :: Eq Bool (alltrue (full n8)) Bool.true;
mt155 := (Eq Tree).refl (full n6);
mt155 :: Eq Tree (mirror (full n6)) (full n6);
ft156 := (Eq Bool).refl Bool.true;
ft156 :: Eq Bool (alltrue (full n7)) Bool.true;
mt156 := (Eq Tree).refl (full n9);
mt156 :: Eq Tree (mirror (full n9)) (full n9);
ft157 := (Eq Bool).refl Bool.true;
ft157 :: Eq Bool (alltrue (full n12)) Bool.true;
mt157 := (Eq Tree).refl (full n7);
mt157 :: Eq Tree (mirror (full n7)) (full n7);
ft158 := (Eq Bool).refl Bool.true;
ft158 :: Eq Bool (alltrue (full n11)) Bool.true;
mt158 := (Eq Tree).refl (full n10);
mt158 :: Eq Tree (mirror (full n10)) (full n10);
ft159 := (Eq Bool).refl Bool.true;
ft159 :: Eq Bool (alltrue (full n10)) Bool.true;
mt159 := (Eq Tree).refl (full n8);
mt159 :: Eq Tree (mirror (full n8)) (full n8);
ft160 := (Eq Bool).refl Bool.true;
ft160 :: Eq Bool (alltrue (full n9)) Bool.true;
mt160 := (Eq Tree).refl (full n6);
mt160 :: Eq Tree (mirror (full n6)) (full n6);
ft161 := (Eq Bool).refl Bool.true;
ft161 :: Eq Bool (alltrue (full n8)) Bool.true;
mt161 := (Eq Tree).refl (full n9);
mt161 :: Eq Tree (mirror (full n9)) (full n9);
ft162 := (Eq Bool).refl Bool.true;
ft162 :: Eq Bool (alltrue (full n7)) Bool.true;
mt162 := (Eq Tree).refl (full n7);
mt162 :: Eq Tree (mirror (full n7)) (full n7);
ft163 := (Eq Bool).refl Bool.true;
ft163 :: Eq Bool (alltrue (full n12)) Bool.true;
mt163 := (Eq Tree).refl (full n10);
mt163 :: Eq Tree (mirror (full n10)) (full n10);
ft164 := (Eq Bool).refl Bool.true;
ft164 :: Eq Bool (alltrue (full n11)) Bool.true;
mt164 := (Eq Tree).refl (full n8);
mt164 :: Eq Tree (mirror (full n8)) (full n8);
ft165 := (Eq Bool).refl Bool.true;
ft165 :: Eq Bool (alltrue (full n10)) Bool.true;
mt165 := (Eq Tree).refl (full n6);
mt165 :: Eq Tree (mirror (full n6)) (full n6);
ft166 := (Eq Bool).refl Bool.true;
ft166 :: Eq Bool (alltrue (full n9)) Bool.true;
mt166 := (Eq Tree).refl (full n9);
mt166 :: Eq Tree (mirror (full n9)) (full n9);
ft167 := (Eq Bool).refl Bool.true;
ft167 :: Eq Bool (alltrue (full n8)) Bool.true;
mt167 := (Eq Tree).refl (full n7);
mt167 :: Eq Tree (mirror (full n7)) (full n7);
ft168 := (Eq Bool).refl Bool.true;
ft168 :: Eq Bool (alltrue (full n7)) Bool.true;
mt168 := (Eq Tree).refl (full n10);
mt168 :: Eq Tree (mirror (full n10)) (full n10);
ft169 := (Eq Bool).refl Bool.true;
ft169 :: Eq Bool (alltrue (full n12)) Bool.true;
mt169 := (Eq Tree).refl (full n8);
mt169 :: Eq Tree (mirror (full n8)) (full n8);
ft170 := (Eq Bool).refl Bool.true;
ft170 :: Eq Bool (alltrue (full n11)) Bool.true;
mt170 := (Eq Tree).refl (full n6);
mt170 :: Eq Tree (mirror (full n6)) (full n6);
ft171 := (Eq Bool).refl Bool.true;
ft171 :: Eq Bool (alltrue (full n10)) Bool.true;
mt171 := (Eq Tree).refl (full n9);
mt171 :: Eq Tree (mirror (full n9)) (full n9);
ft172 := (Eq Bool).refl Bool.true;
ft172 :: Eq Bool (alltrue (full n9)) Bool.true;
mt172 := (Eq Tree).refl (full n7);
mt172 :: Eq Tree (mirror (full n7)) (full n7);
ft173 := (Eq Bool).refl Bool.true;
ft173 :: Eq Bool (alltrue (full n8)) Bool.true;
mt173 := (Eq Tree).refl (full n10);
mt173 :: Eq Tree (mirror (full n10)) (full n10);
ft174 := (Eq Bool).refl Bool.true;
ft174 :: Eq Bool (alltrue (full n7)) Bool.true;
mt174 := (Eq Tree).refl (full n8);
mt174 :: Eq Tree (mirror (full n8)) (full n8);
ft175 := (Eq Bool).refl Bool.true;
ft175 :: Eq Bool (alltrue (full n12)) Bool.true;
mt175 := (Eq Tree).refl (full n6);
mt175 :: Eq Tree (mirror (full n6)) (full n6);
ft176 := (Eq Bool).refl Bool.true;
ft176 :: Eq Bool (alltrue (full n11)) Bool.true;
mt176 := (Eq Tree).refl (full n9);
mt176 :: Eq Tree (mirror (full n9)) (full n9);
ft177 := (Eq Bool).refl Bool.true;
ft177 :: Eq Bool (alltrue (full n10)) Bool.true;
mt177 := (Eq Tree).refl (full n7);
mt177 :: Eq Tree (mirror (full n7)) (full n7);
ft178 := (Eq Bool).refl Bool.true;
ft178 :: Eq Bool (alltrue (full n9)) Bool.true;
mt178 := (Eq Tree).refl (full n10);
mt178 :: Eq Tree (mirror (full n10)) (full n10);
ft179 := (Eq Bool).refl Bool.true;
ft179 :: Eq Bool (alltrue (full n8)) Bool.true;
mt179 := (Eq Tree).refl (full n8);
mt179 :: Eq Tree (mirror (full n8)) (full n8);
ft180 := (Eq Bool).refl Bool.true;
ft180 :: Eq Bool (alltrue (full n7)) Bool.true;
mt180 := (Eq Tree).refl (full n6);
mt180 :: Eq Tree (mirror (full n6)) (full n6);
ft181 := (Eq Bool).refl Bool.true;
ft181 :: Eq Bool (alltrue (full n12)) Bool.true;
mt181 := (Eq Tree).refl (full n9);
mt181 :: Eq Tree (mirror (full n9)) (full n9);
ft182 := (Eq Bool).refl Bool.true;
ft182 :: Eq Bool (alltrue (full n11)) Bool.true;
mt182 := (Eq Tree).refl (full n7);
mt182 :: Eq Tree (mirror (full n7)) (full n7);
ft183 := (Eq Bool).refl Bool.true;
ft183 :: Eq Bool (alltrue (full n10)) Bool.true;
mt183 := (Eq Tree).refl (full n10);
mt183 :: Eq Tree (mirror (full n10)) (full n10);
ft184 := (Eq Bool).refl Bool.true;
ft184 :: Eq Bool (alltrue (full n9)) Bool.true;
mt184 := (Eq Tree).refl (full n8);
mt184 :: Eq Tree (mirror (full n8)) (full n8);
ft185 := (Eq Bool).refl Bool.true;
ft185 :: Eq Bool (alltrue (full n8)) Bool.true;
mt185 := (Eq Tree).refl (full n6);
mt185 :: Eq Tree (mirror (full n6)) (full n6);
ft186 := (Eq Bool).refl Bool.true;
ft186 :: Eq Bool (alltrue (full n7)) Bool.true;
mt186 := (Eq Tree).refl (full n9);
mt186 :: Eq Tree (mirror (full n9)) (full n9);
ft187 := (Eq Bool).refl Bool.true;
ft187 :: Eq Bool (alltrue (full n12)) Bool.true;
mt187 := (Eq Tree).refl (full n7);
mt187 :: Eq Tree (mirror (full n7)) (full n7);
ft188 := (Eq Bool).refl Bool.true;
ft188 :: Eq Bool (alltrue (full n11)) Bool.true;
mt188 := (Eq Tree).refl (full n10);
mt188 :: Eq Tree (mirror (full n10)) (full n10);
ft189 := (Eq Bool).refl Bool.true;
ft189 :: Eq Bool (alltrue (full n10)) Bool.true;
mt189 := (Eq Tree).refl (full n8);
mt189 :: Eq Tree (mirror (full n8)) (full n8);
ft190 := (Eq Bool).refl Bool.true;
ft190 :: Eq Bool (alltrue (full n9)) Bool.true;
mt190 := (Eq Tree).refl (full n6);
mt190 :: Eq Tree (mirror (full n6)) (full n6);
ft191 := (Eq Bool).refl Bool.true;
ft191 :: Eq Bool (alltrue (full n8)) Bool.true;
mt191 := (Eq Tree).refl (full n9);
mt191 :: Eq Tree (mirror (full n9)) (full n9);
ft192 := (Eq Bool).refl Bool.true;
ft192 :: Eq Bool (alltrue (full n7)) Bool.true;
mt192 := (Eq Tree).refl (full n7);
mt192 :: Eq Tree (mirror (full n7)) (full n7);
ft193 := (Eq Bool).refl Bool.true;
ft193 :: Eq Bool (alltrue (full n12)) Bool.true;
mt193 := (Eq Tree).refl (full n10);
mt193 :: Eq Tree (mirror (full n10)) (full n10);
ft194 := (Eq Bool).refl Bool.true;
ft194 :: Eq Bool (alltrue (full n11)) Bool.true;
mt194 := (Eq Tree).refl (full n8);
mt194 :: Eq Tree (mirror (full n8)) (full n8);
ft195 := (Eq Bool).refl Bool.true;
ft195 :: Eq Bool (alltrue (full n10)) Bool.true;
mt195 := (Eq Tree).refl (full n6);
mt195 :: Eq Tree (mirror (full n6)) (full n6);
ft196 := (Eq Bool).refl Bool.true;
ft196 :: Eq Bool (alltrue (full n9)) Bool.true;
mt196 := (Eq Tree).refl (full n9);
mt196 :: Eq Tree (mirror (full n9)) (full n9);
ft197 := (Eq Bool).refl Bool.true;
ft197 :: Eq Bool (alltrue (full n8)) Bool.true;
mt197 := (Eq Tree).refl (full n7);
mt197 :: Eq Tree (mirror (full n7)) (full n7);
ft198 := (Eq Bool).refl Bool.true;
ft198 :: Eq Bool (alltrue (full n7)) Bool.true;
mt198 := (Eq Tree).refl (full n10);
mt198 :: Eq Tree (mirror (full n10)) (full n10);
ft199 := (Eq Bool).refl Bool.true;
ft199 :: Eq Bool (alltrue (full n12)) Bool.true;
mt199 := (Eq Tree).refl (full n8);
mt199 :: Eq Tree (mirror (full n8)) (full n8);
ft200 := (Eq Bool).refl Bool.true;
ft200 :: Eq Bool (alltrue (full n11)) Bool.true;
mt200 := (Eq Tree).refl (full n6);
mt200 :: Eq Tree (mirror (full n6)) (full n6);
ft201 := (Eq Bool).refl Bool.true;
ft201 :: Eq Bool (alltrue (full n10)) Bool.true;
mt201 := (Eq Tree).refl (full n9);
mt201 :: Eq Tree (mirror (full n9)) (full n9);
ft202 := (Eq Bool).refl Bool.true;
ft202 :: Eq Bool (alltrue (full n9)) Bool.true;
mt202 := (Eq Tree).refl (full n7);
mt202 :: Eq Tree (mirror (full n7)) (full n7);
ft203 := (Eq Bool).refl Bool.true;
ft203 :: Eq Bool (alltrue (full n8)) Bool.true;
mt203 := (Eq Tree).refl (full n10);
mt203 :: Eq Tree (mirror (full n10)) (full n10);
ft204 := (Eq Bool).refl Bool.true;
ft204 :: Eq Bool (alltrue (full n7)) Bool.true;
mt204 := (Eq Tree).refl (full n8);
mt204 :: Eq Tree (mirror (full n8)) (full n8);
ft205 := (Eq Bool).refl Bool.true;
ft205 :: Eq Bool (alltrue (full n12)) Bool.true;
mt205 := (Eq Tree).refl (full n6);
mt205 :: Eq Tree (mirror (full n6)) (full n6);
ft206 := (Eq Bool).refl Bool.true;
ft206 :: Eq Bool (alltrue (full n11)) Bool.true;
mt206 := (Eq Tree).refl (full n9);
mt206 :: Eq Tree (mirror (full n9)) (full n9);
ft207 := (Eq Bool).refl Bool.true;
ft207 :: Eq Bool (alltrue (full n10)) Bool.true;
mt207 := (Eq Tree).refl (full n7);
mt207 :: Eq Tree (mirror (full n7)) (full n7);
ft208 := (Eq Bool).refl Bool.true;
ft208 :: Eq Bool (alltrue (full n9)) Bool.true;
mt208 := (Eq Tree).refl (full n10);
mt208 :: Eq Tree (mirror (full n10)) (full n10);
ft209 := (Eq Bool).refl Bool.true;
ft209 :: Eq Bool (alltrue (full n8)) Bool.true;
mt209 := (Eq Tree).refl (full n8);
mt209 :: Eq Tree (mirror (full n8)) (full n8);
ft210 := (Eq Bool).refl Bool.true;
ft210 :: Eq Bool (alltrue (full n7)) Bool.true;
mt210 := (Eq Tree).refl (full n6);
mt210 :: Eq Tree (mirror (full n6)) (full n6);
ft211 := (Eq Bool).refl Bool.true;
ft211 :: Eq Bool (alltrue (full n12)) Bool.true;
mt211 := (Eq Tree).refl (full n9);
mt211 :: Eq Tree (mirror (full n9)) (full n9);
ft212 := (Eq Bool).refl Bool.true;
ft212 :: Eq Bool (alltrue (full n11)) Bool.true;
mt212 := (Eq Tree).refl (full n7);
mt212 :: Eq Tree (mirror (full n7)) (full n7);
ft213 := (Eq Bool).refl Bool.true;
ft213 :: Eq Bool (alltrue (full n10)) Bool.true;
mt213 := (Eq Tree).refl (full n10);
mt213 :: Eq Tree (mirror (full n10)) (full n10);
ft214 := (Eq Bool).refl Bool.true;
ft214 :: Eq Bool (alltrue (full n9)) Bool.true;
mt214 := (Eq Tree).refl (full n8);
mt214 :: Eq Tree (mirror (full n8)) (full n8);
ft215 := (Eq Bool).refl Bool.true;
ft215 :: Eq Bool (alltrue (full n8)) Bool.true;
mt215 := (Eq Tree).refl (full n6);
mt215 :: Eq Tree (mirror (full n6)) (full n6);
ft216 := (Eq Bool).refl Bool.true;
ft216 :: Eq Bool (alltrue (full n7)) Bool.true;
mt216 := (Eq Tree).refl (full n9);
mt216 :: Eq Tree (mirror (full n9)) (full n9);
ft217 := (Eq Bool).refl Bool.true;
ft217 :: Eq Bool (alltrue (full n12)) Bool.true;
mt217 := (Eq Tree).refl (full n7);
mt217 :: Eq Tree (mirror (full n7)) (full n7);
ft218 := (Eq Bool).refl Bool.true;
ft218 :: Eq Bool (alltrue (full n11)) Bool.true;
mt218 := (Eq Tree).refl (full n10);
mt218 :: Eq Tree (mirror (full n10)) (full n10);
ft219 := (Eq Bool).refl Bool.true;
ft219 :: Eq Bool (alltrue (full n10)) Bool.true;
mt219 := (Eq Tree).refl (full n8);
mt219 :: Eq Tree (mirror (full n8)) (full n8);
ft220 := (Eq Bool).refl Bool.true;
ft220 :: Eq Bool (alltrue (full n9)) Bool.true;
mt220 := (Eq Tree).refl (full n6);
mt220 :: Eq Tree (mirror (full n6)) (full n6);
ft221 := (Eq Bool).refl Bool.true;
ft221 :: Eq Bool (alltrue (full n8)) Bool.true;
mt221 := (Eq Tree).refl (full n9);
mt221 :: Eq Tree (mirror (full n9)) (full n9);
ft222 := (Eq Bool).refl Bool.true;
ft222 :: Eq Bool (alltrue (full n7)) Bool.true;
mt222 := (Eq Tree).refl (full n7);
mt222 :: Eq Tree (mirror (full n7)) (full n7);
ft223 := (Eq Bool).refl Bool.true;
ft223 :: Eq Bool (alltrue (full n12)) Bool.true;
mt223 := (Eq Tree).refl (full n10);
mt223 :: Eq Tree (mirror (full n10)) (full n10);
ft224 := (Eq Bool).refl Bool.true;
ft224 :: Eq Bool (alltrue (full n11)) Bool.true;
mt224 := (Eq Tree).refl (full n8);
mt224 :: Eq Tree (mirror (full n8)) (full n8);
ft225 := (Eq Bool).refl Bool.true;
ft225 :: Eq Bool (alltrue (full n10)) Bool.true;
mt225 := (Eq Tree).refl (full n6);
mt225 :: Eq Tree (mirror (full n6)) (full n6);
ft226 := (Eq Bool).refl Bool.true;
ft226 :: Eq Bool (alltrue (full n9)) Bool.true;
mt226 := (Eq Tree).refl (full n9);
mt226 :: Eq Tree (mirror (full n9)) (full n9);
ft227 := (Eq Bool).refl Bool.true;
ft227 :: Eq Bool (alltrue (full n8)) Bool.true;
mt227 := (Eq Tree).refl (full n7);
mt227 :: Eq Tree (mirror (full n7)) (full n7);
ft228 := (Eq Bool).refl Bool.true;
ft228 :: Eq Bool (alltrue (full n7)) Bool.true;
mt228 := (Eq Tree).refl (full n10);
mt228 :: Eq Tree (mirror (full n10)) (full n10);
ft229 := (Eq Bool).refl Bool.true;
ft229 :: Eq Bool (alltrue (full n12)) Bool.true;
mt229 := (Eq Tree).refl (full n8);
mt229 :: Eq Tree (mirror (full n8)) (full n8);
ft230 := (Eq Bool).refl Bool.true;
ft230 :: Eq Bool (alltrue (full n11)) Bool.true;
mt230 := (Eq Tree).refl (full n6);
mt230 :: Eq Tree (mirror (full n6)) (full n6);
ft231 := (Eq Bool).refl Bool.true;
ft231 :: Eq Bool (alltrue (full n10)) Bool.true;
mt231 := (Eq Tree).refl (full n9);
mt231 :: Eq Tree (mirror (full n9)) (full n9);
ft232 := (Eq Bool).refl Bool.true;
ft232 :: Eq Bool (alltrue (full n9)) Bool.true;
mt232 := (Eq Tree).refl (full n7);
mt232 :: Eq Tree (mirror (full n7)) (full n7);
ft233 := (Eq Bool).refl Bool.true;
ft233 :: Eq Bool (alltrue (full n8)) Bool.true;
mt233 := (Eq Tree).refl (full n10);
mt233 :: Eq Tree (mirror (full n10)) (full n10);
ft234 := (Eq Bool).refl Bool.true;
ft234 :: Eq Bool (alltrue (full n7)) Bool.true;
mt234 := (Eq Tree).refl (full n8);
mt234 :: Eq Tree (mirror (full n8)) (full n8);
ft235 := (Eq Bool).refl Bool.true;
ft235 :: Eq Bool (alltrue (full n12)) Bool.true;
mt235 := (Eq Tree).refl (full n6);
mt235 :: Eq Tree (mirror (full n6)) (full n6);
ft236 := (Eq Bool).refl Bool.true;
ft236 :: Eq Bool (alltrue (full n11)) Bool.true;
mt236 := (Eq Tree).refl (full n9);
mt236 :: Eq Tree (mirror (full n9)) (full n9);
ft237 := (Eq Bool).refl Bool.true;
ft237 :: Eq Bool (alltrue (full n10)) Bool.true;
mt237 := (Eq Tree).refl (full n7);
mt237 :: Eq Tree (mirror (full n7)) (full n7);
ft238 := (Eq Bool).refl Bool.true;
ft238 :: Eq Bool (alltrue (full n9)) Bool.true;
mt238 := (Eq Tree).refl (full n10);
mt238 :: Eq Tree (mirror (full n10)) (full n10);
ft239 := (Eq Bool).refl Bool.true;
ft239 :: Eq Bool (alltrue (full n8)) Bool.true;
mt239 := (Eq Tree).refl (full n8);
mt239 :: Eq Tree (mirror (full n8)) (full n8);
ft240 := (Eq Bool).refl Bool.true;
ft240 :: Eq Bool (alltrue (full n7)) Bool.true;
mt240 := (Eq Tree).refl (full n6);
mt240 :: Eq Tree (mirror (full n6)) (full n6);
ft241 := (Eq Bool).refl Bool.true;
ft241 :: Eq Bool (alltrue (full n12)) Bool.true;
mt241 := (Eq Tree).refl (full n9);
mt241 :: Eq Tree (mirror (full n9)) (full n9);
ft242 := (Eq Bool).refl Bool.true;
ft242 :: Eq Bool (alltrue (full n11)) Bool.true;
mt242 := (Eq Tree).refl (full n7);
mt242 :: Eq Tree (mirror (full n7)) (full n7);
ft243 := (Eq Bool).refl Bool.true;
ft243 :: Eq Bool (alltrue (full n10)) Bool.true;
mt243 := (Eq Tree).refl (full n10);
mt243 :: Eq Tree (mirror (full n10)) (full n10);
ft244 := (Eq Bool).refl Bool.true;
ft244 :: Eq Bool (alltrue (full n9)) Bool.true;
mt244 := (Eq Tree).refl (full n8);
mt244 :: Eq Tree (mirror (full n8)) (full n8);
ft245 := (Eq Bool).refl Bool.true;
ft245 :: Eq Bool (alltrue (full n8)) Bool.true;
mt245 := (Eq Tree).refl (full n6);
mt245 :: Eq Tree (mirror (full n6)) (full n6);
ft246 := (Eq Bool).refl Bool.true;
ft246 :: Eq Bool (alltrue (full n7)) Bool.true;
mt246 := (Eq Tree).refl (full n9);
mt246 :: Eq Tree (mirror (full n9)) (full n9);
ft247 := (Eq Bool).refl Bool.true;
ft247 :: Eq Bool (alltrue (full n12)) Bool.true;
mt247 := (Eq Tree).refl (full n7);
mt247 :: Eq Tree (mirror (full n7)) (full n7);
ft248 := (Eq Bool).refl Bool.true;
ft248 :: Eq Bool (alltrue (full n11)) Bool.true;
mt248 := (Eq Tree).refl (full n10);
mt248 :: Eq Tree (mirror (full n10)) (full n10);
ft249 := (Eq Bool).refl Bool.true;
ft249 :: Eq Bool (alltrue (full n10)) Bool.true;
mt249 := (Eq Tree).refl (full n8);
mt249 :: Eq Tree (mirror (full n8)) (full n8);
ft250 := (Eq Bool).refl Bool.true;
ft250 :: Eq Bool (alltrue (full n9)) Bool.true;
mt250 := (Eq Tree).refl (full n6);
mt250 :: Eq Tree (mirror (full n6)) (full n6);
ft251 := (Eq Bool).refl Bool.true;
ft251 :: Eq Bool (alltrue (full n8)) Bool.true;
mt251 := (Eq Tree).refl (full n9);
mt251 :: Eq Tree (mirror (full n9)) (full n9);
ft252 := (Eq Bool).refl Bool.true;
ft252 :: Eq Bool (alltrue (full n7)) Bool.true;
mt252 := (Eq Tree).refl (full n7);
mt252 :: Eq Tree (mirror (full n7)) (full n7);
ft253 := (Eq Bool).refl Bool.true;
ft253 :: Eq Bool (alltrue (full n12)) Bool.true;
mt253 := (Eq Tree).refl (full n10);
mt253 :: Eq Tree (mirror (full n10)) (full n10);
ft254 := (Eq Bool).refl Bool.true;
ft254 :: Eq Bool (alltrue (full n11)) Bool.true;
mt254 := (Eq Tree).refl (full n8);
mt254 :: Eq Tree (mirror (full n8)) (full n8);
ft255 := (Eq Bool).refl Bool.true;
ft255 :: Eq Bool (alltrue (full n10)) Bool.true;
mt255 := (Eq Tree).refl (full n6);
mt255 :: Eq Tree (mirror (full n6)) (full n6);
ft256 := (Eq Bool).refl Bool.true;
ft256 :: Eq Bool (alltrue (full n9)) Bool.true;
mt256 := (Eq Tree).refl (full n9);
mt256 :: Eq Tree (mirror (full n9)) (full n9);
ft257 := (Eq Bool).refl Bool.true;
ft257 :: Eq Bool (alltrue (full n8)) Bool.true;
mt257 := (Eq Tree).refl (full n7);
mt257 :: Eq Tree (mirror (full n7)) (full n7);
ft258 := (Eq Bool).refl Bool.true;
ft258 :: Eq Bool (alltrue (full n7)) Bool.true;
mt258 := (Eq Tree).refl (full n10);
mt258 :: Eq Tree (mirror (full n10)) (full n10);
ft259 := (Eq Bool).refl Bool.true;
ft259 :: Eq Bool (alltrue (full n12)) Bool.true;
mt259 := (Eq Tree).refl (full n8);
mt259 :: Eq Tree (mirror (full n8)) (full n8);
ft260 := (Eq Bool).refl Bool.true;
ft260 :: Eq Bool (alltrue (full n11)) Bool.true;
mt260 := (Eq Tree).refl (full n6);
mt260 :: Eq Tree (mirror (full n6)) (full n6);
ft261 := (Eq Bool).refl Bool.true;
ft261 :: Eq Bool (alltrue (full n10)) Bool.true;
mt261 := (Eq Tree).refl (full n9);
mt261 :: Eq Tree (mirror (full n9)) (full n9);
ft262 := (Eq Bool).refl Bool.true;
ft262 :: Eq Bool (alltrue (full n9)) Bool.true;
mt262 := (Eq Tree).refl (full n7);
mt262 :: Eq Tree (mirror (full n7)) (full n7);
ft263 := (Eq Bool).refl Bool.true;
ft263 :: Eq Bool (alltrue (full n8)) Bool.true;
mt263 := (Eq Tree).refl (full n10);
mt263 :: Eq Tree (mirror (full n10)) (full n10);
ft264 := (Eq Bool).refl Bool.true;
ft264 :: Eq Bool (alltrue (full n7)) Bool.true;
mt264 := (Eq Tree).refl (full n8);
mt264 :: Eq Tree (mirror (full n8)) (full n8);
ft265 := (Eq Bool).refl Bool.true;
ft265 :: Eq Bool (alltrue (full n12)) Bool.true;
mt265 := (Eq Tree).refl (full n6);
mt265 :: Eq Tree (mirror (full n6)) (full n6);
ft266 := (Eq Bool).refl Bool.true;
ft266 :: Eq Bool (alltrue (full n11)) Bool.true;
mt266 := (Eq Tree).refl (full n9);
mt266 :: Eq Tree (mirror (full n9)) (full n9);
ft267 := (Eq Bool).refl Bool.true;
ft267 :: Eq Bool (alltrue (full n10)) Bool.true;
mt267 := (Eq Tree).refl (full n7);
mt267 :: Eq Tree (mirror (full n7)) (full n7);
ft268 := (Eq Bool).refl Bool.true;
ft268 :: Eq Bool (alltrue (full n9)) Bool.true;
mt268 := (Eq Tree).refl (full n10);
mt268 :: Eq Tree (mirror (full n10)) (full n10);
ft269 := (Eq Bool).refl Bool.true;
ft269 :: Eq Bool (alltrue (full n8)) Bool.true;
mt269 := (Eq Tree).refl (full n8);
mt269 :: Eq Tree (mirror (full n8)) (full n8);
ft270 := (Eq Bool).refl Bool.true;
ft270 :: Eq Bool (alltrue (full n7)) Bool.true;
mt270 := (Eq Tree).refl (full n6);
mt270 :: Eq Tree (mirror (full n6)) (full n6);
ft271 := (Eq Bool).refl Bool.true;
ft271 :: Eq Bool (alltrue (full n12)) Bool.true;
mt271 := (Eq Tree).refl (full n9);
mt271 :: Eq Tree (mirror (full n9)) (full n9);
ft272 := (Eq Bool).refl Bool.true;
ft272 :: Eq Bool (alltrue (full n11)) Bool.true;
mt272 := (Eq Tree).refl (full n7);
mt272 :: Eq Tree (mirror (full n7)) (full n7);
ft273 := (Eq Bool).refl Bool.true;
ft273 :: Eq Bool (alltrue (full n10)) Bool.true;
mt273 := (Eq Tree).refl (full n10);
mt273 :: Eq Tree (mirror (full n10)) (full n10);
ft274 := (Eq Bool).refl Bool.true;
ft274 :: Eq Bool (alltrue (full n9)) Bool.true;
mt274 := (Eq Tree).refl (full n8);
mt274 :: Eq Tree (mirror (full n8)) (full n8);
ft275 := (Eq Bool).refl Bool.true;
ft275 :: Eq Bool (alltrue (full n8)) Bool.true;
mt275 := (Eq Tree).refl (full n6);
mt275 :: Eq Tree (mirror (full n6)) (full n6);
ft276 := (Eq Bool).refl Bool.true;
ft276 :: Eq Bool (alltrue (full n7)) Bool.true;
mt276 := (Eq Tree).refl (full n9);
mt276 :: Eq Tree (mirror (full n9)) (full n9);
ft277 := (Eq Bool).refl Bool.true;
ft277 :: Eq Bool (alltrue (full n12)) Bool.true;
mt277 := (Eq Tree).refl (full n7);
mt277 :: Eq Tree (mirror (full n7)) (full n7);
ft278 := (Eq Bool).refl Bool.true;
ft278 :: Eq Bool (alltrue (full n11)) Bool.true;
mt278 := (Eq Tree).refl (full n10);
mt278 :: Eq Tree (mirror (full n10)) (full n10);
ft279 := (Eq Bool).refl Bool.true;
ft279 :: Eq Bool (alltrue (full n10)) Bool.true;
mt279 := (Eq Tree).refl (full n8);
mt279 :: Eq Tree (mirror (full n8)) (full n8);
ft280 := (Eq Bool).refl Bool.true;
ft280 :: Eq Bool (alltrue (full n9)) Bool.true;
mt280 := (Eq Tree).refl (full n6);
mt280 :: Eq Tree (mirror (full n6)) (full n6);
ft281 := (Eq Bool).refl Bool.true;
ft281 :: Eq Bool (alltrue (full n8)) Bool.true;
mt281 := (Eq Tree).refl (full n9);
mt281 :: Eq Tree (mirror (full n9)) (full n9);
ft282 := (Eq Bool).refl Bool.true;
ft282 :: Eq Bool (alltrue (full n7)) Bool.true;
mt282 := (Eq Tree).refl (full n7);
mt282 :: Eq Tree (mirror (full n7)) (full n7);
ft283 := (Eq Bool).refl Bool.true;
ft283 :: Eq Bool (alltrue (full n12)) Bool.true;
mt283 := (Eq Tree).refl (full n10);
mt283 :: Eq Tree (mirror (full n10)) (full n10);
ft284 := (Eq Bool).refl Bool.true;
ft284 :: Eq Bool (alltrue (full n11)) Bool.true;
mt284 := (Eq Tree).refl (full n8);
mt284 :: Eq Tree (mirror (full n8)) (full n8);
ft285 := (Eq Bool).refl Bool.true;
ft285 :: Eq Bool (alltrue (full n10)) Bool.true;
mt285 := (Eq Tree).refl (full n6);
mt285 :: Eq Tree (mirror (full n6)) (full n6);
ft286 := (Eq Bool).refl Bool.true;
ft286 :: Eq Bool (alltrue (full n9)) Bool.true;
mt286 := (Eq Tree).refl (full n9);
mt286 :: Eq Tree (mirror (full n9)) (full n9);
ft287 := (Eq Bool).refl Bool.true;
ft287 :: Eq Bool (alltrue (full n8)) Bool.true;
mt287 := (Eq Tree).refl (full n7);
mt287 :: Eq Tree (mirror (full n7)) (full n7);
ft288 := (Eq Bool).refl Bool.true;
ft288 :: Eq Bool (alltrue (full n7)) Bool.true;
mt288 := (Eq Tree).refl (full n10);
mt288 :: Eq Tree (mirror (full n10)) (full n10);
ft289 := (Eq Bool).refl Bool.true;
ft289 :: Eq Bool (alltrue (full n12)) Bool.true;
mt289 := (Eq Tree).refl (full n8);
mt289 :: Eq Tree (mirror (full n8)) (full n8);
ft290 := (Eq Bool).refl Bool.true;
ft290 :: Eq Bool (alltrue (full n11)) Bool.true;
mt290 := (Eq Tree).refl (full n6);
mt290 :: Eq Tree (mirror (full n6)) (full n6);
ft291 := (Eq Bool).refl Bool.true;
ft291 :: Eq Bool (alltrue (full n10)) Bool.true;
mt291 := (Eq Tree).refl (full n9);
mt291 :: Eq Tree (mirror (full n9)) (full n9);
ft292 := (Eq Bool).refl Bool.true;
ft292 :: Eq Bool (alltrue (full n9)) Bool.true;
mt292 := (Eq Tree).refl (full n7);
mt292 :: Eq Tree (mirror (full n7)) (full n7);
ft293 := (Eq Bool).refl Bool.true;
ft293 :: Eq Bool (alltrue (full n8)) Bool.true;
mt293 := (Eq Tree).refl (full n10);
mt293 :: Eq Tree (mirror (full n10)) (full n10);
ft294 := (Eq Bool).refl Bool.true;
ft294 :: Eq Bool (alltrue (full n7)) Bool.true;
mt294 := (Eq Tree).refl (full n8);
mt294 :: Eq Tree (mirror (full n8)) (full n8);
ft295 := (Eq Bool).refl Bool.true;
ft295 :: Eq Bool (alltrue (full n12)) Bool.true;
mt295 := (Eq Tree).refl (full n6);
mt295 :: Eq Tree (mirror (full n6)) (full n6);
ft296 := (Eq Bool).refl Bool.true;
ft296 :: Eq Bool (alltrue (full n11)) Bool.true;
mt296 := (Eq Tree).refl (full n9);
mt296 :: Eq Tree (mirror (full n9)) (full n9);
ft297 := (Eq Bool).refl Bool.true;
ft297 :: Eq Bool (alltrue (full n10)) Bool.true;
mt297 := (Eq Tree).refl (full n7);
mt297 :: Eq Tree (mirror (full n7)) (full n7);
ft298 := (Eq Bool).refl Bool.true;
ft298 :: Eq Bool (alltrue (full n9)) Bool.true;
mt298 := (Eq Tree).refl (full n10);
mt298 :: Eq Tree (mirror (full n10)) (full n10);
ft299 := (Eq Bool).refl Bool.true;
ft299 :: Eq Bool (alltrue (full n8)) Bool.true;
mt299 := (Eq Tree).refl (full n8);
mt299 :: Eq Tree (mirror (full n8)) (full n8);
ft300 := (Eq Bool).refl Bool.true;
ft300 :: Eq Bool (alltrue (full n7)) Bool.true;
mt300 := (Eq Tree).refl (full n6);
mt300 :: Eq Tree (mirror (full n6)) (full n6);
ft301 := (Eq Bool).refl Bool.true;
ft301 :: Eq Bool (alltrue (full n12)) Bool.true;
mt301 := (Eq Tree).refl (full n9);
mt301 :: Eq Tree (mirror (full n9)) (full n9);
ft302 := (Eq Bool).refl Bool.true;
ft302 :: Eq Bool (alltrue (full n11)) Bool.true;
mt302 := (Eq Tree).refl (full n7);
mt302 :: Eq Tree (mirror (full n7)) (full n7);
ft303 := (Eq Bool).refl Bool.true;
ft303 :: Eq Bool (alltrue (full n10)) Bool.true;
mt303 := (Eq Tree).refl (full n10);
mt303 :: Eq Tree (mirror (full n10)) (full n10);
ft304 := (Eq Bool).refl Bool.true;
ft304 :: Eq Bool (alltrue (full n9)) Bool.true;
mt304 := (Eq Tree).refl (full n8);
mt304 :: Eq Tree (mirror (full n8)) (full n8);
ft305 := (Eq Bool).refl Bool.true;
ft305 :: Eq Bool (alltrue (full n8)) Bool.true;
mt305 := (Eq Tree).refl (full n6);
mt305 :: Eq Tree (mirror (full n6)) (full n6);
ft306 := (Eq Bool).refl Bool.true;
ft306 :: Eq Bool (alltrue (full n7)) Bool.true;
mt306 := (Eq Tree).refl (full n9);
mt306 :: Eq Tree (mirror (full n9)) (full n9);
ft307 := (Eq Bool).refl Bool.true;
ft307 :: Eq Bool (alltrue (full n12)) Bool.true;
mt307 := (Eq Tree).refl (full n7);
mt307 :: Eq Tree (mirror (full n7)) (full n7);
ft308 := (Eq Bool).refl Bool.true;
ft308 :: Eq Bool (alltrue (full n11)) Bool.true;
mt308 := (Eq Tree).refl (full n10);
mt308 :: Eq Tree (mirror (full n10)) (full n10);
ft309 := (Eq Bool).refl Bool.true;
ft309 :: Eq Bool (alltrue (full n10)) Bool.true;
mt309 := (Eq Tree).refl (full n8);
mt309 :: Eq Tree (mirror (full n8)) (full n8);
ft310 := (Eq Bool).refl Bool.true;
ft310 :: Eq Bool (alltrue (full n9)) Bool.true;
mt310 := (Eq Tree).refl (full n6);
mt310 :: Eq Tree (mirror (full n6)) (full n6);
ft311 := (Eq Bool).refl Bool.true;
ft311 :: Eq Bool (alltrue (full n8)) Bool.true;
mt311 := (Eq Tree).refl (full n9);
mt311 :: Eq Tree (mirror (full n9)) (full n9);
ft312 := (Eq Bool).refl Bool.true;
ft312 :: Eq Bool (alltrue (full n7)) Bool.true;
mt312 := (Eq Tree).refl (full n7);
mt312 :: Eq Tree (mirror (full n7)) (full n7);
ft313 := (Eq Bool).refl Bool.true;
ft313 :: Eq Bool (alltrue (full n12)) Bool.true;
mt313 := (Eq Tree).refl (full n10);
mt313 :: Eq Tree (mirror (full n10)) (full n10);
ft314 := (Eq Bool).refl Bool.true;
ft314 :: Eq Bool (alltrue (full n11)) Bool.true;
mt314 := (Eq Tree).refl (full n8);
mt314 :: Eq Tree (mirror (full n8)) (full n8);
ft315 := (Eq Bool).refl Bool.true;
ft315 :: Eq Bool (alltrue (full n10)) Bool.true;
mt315 := (Eq Tree).refl (full n6);
mt315 :: Eq Tree (mirror (full n6)) (full n6);
ft316 := (Eq Bool).refl Bool.true;
ft316 :: Eq Bool (alltrue (full n9)) Bool.true;
mt316 := (Eq Tree).refl (full n9);
mt316 :: Eq Tree (mirror (full n9)) (full n9);
ft317 := (Eq Bool).refl Bool.true;
ft317 :: Eq Bool (alltrue (full n8)) Bool.true;
mt317 := (Eq Tree).refl (full n7);
mt317 :: Eq Tree (mirror (full n7)) (full n7);
ft318 := (Eq Bool).refl Bool.true;
ft318 :: Eq Bool (alltrue (full n7)) Bool.true;
mt318 := (Eq Tree).refl (full n10);
mt318 :: Eq Tree (mirror (full n10)) (full n10);
ft319 := (Eq Bool).refl Bool.true;
ft319 :: Eq Bool (alltrue (full n12)) Bool.true;
mt319 := (Eq Tree).refl (full n8);
mt319 :: Eq Tree (mirror (full n8)) (full n8);
ft320 := (Eq Bool).refl Bool.true;
ft320 :: Eq Bool (alltrue (full n11)) Bool.true;
mt320 := (Eq Tree).refl (full n6);
mt320 :: Eq Tree (mirror (full n6)) (full n6);
ft321 := (Eq Bool).refl Bool.true;
ft321 :: Eq Bool (alltrue (full n10)) Bool.true;
mt321 := (Eq Tree).refl (full n9);
mt321 :: Eq Tree (mirror (full n9)) (full n9);
ft322 := (Eq Bool).refl Bool.true;
ft322 :: Eq Bool (alltrue (full n9)) Bool.true;
mt322 := (Eq Tree).refl (full n7);
mt322 :: Eq Tree (mirror (full n7)) (full n7);
ft323 := (Eq Bool).refl Bool.true;
ft323 :: Eq Bool (alltrue (full n8)) Bool.true;
mt323 := (Eq Tree).refl (full n10);
mt323 :: Eq Tree (mirror (full n10)) (full n10);
ft324 := (Eq Bool).refl Bool.true;
ft324 :: Eq Bool (alltrue (full n7)) Bool.true;
mt324 := (Eq Tree).refl (full n8);
mt324 :: Eq Tree (mirror (full n8)) (full n8);
ft325 := (Eq Bool).refl Bool.true;
ft325 :: Eq Bool (alltrue (full n12)) Bool.true;
mt325 := (Eq Tree).refl (full n6);
mt325 :: Eq Tree (mirror (full n6)) (full n6);
ft326 := (Eq Bool).refl Bool.true;
ft326 :: Eq Bool (alltrue (full n11)) Bool.true;
mt326 := (Eq Tree).refl (full n9);
mt326 :: Eq Tree (mirror (full n9)) (full n9);
ft327 := (Eq Bool).refl Bool.true;
ft327 :: Eq Bool (alltrue (full n10)) Bool.true;
mt327 := (Eq Tree).refl (full n7);
mt327 :: Eq Tree (mirror (full n7)) (full n7);
ft328 := (Eq Bool).refl Bool.true;
ft328 :: Eq Bool (alltrue (full n9)) Bool.true;
mt328 := (Eq Tree).refl (full n10);
mt328 :: Eq Tree (mirror (full n10)) (full n10);
ft329 := (Eq Bool).refl Bool.true;
ft329 :: Eq Bool (alltrue (full n8)) Bool.true;
mt329 := (Eq Tree).refl (full n8);
mt329 :: Eq Tree (mirror (full n8)) (full n8);
ft330 := (Eq Bool).refl Bool.true;
ft330 :: Eq Bool (alltrue (full n7)) Bool.true;
mt330 := (Eq Tree).refl (full n6);
mt330 :: Eq Tree (mirror (full n6)) (full n6);
ft331 := (Eq Bool).refl Bool.true;
ft331 :: Eq Bool (alltrue (full n12)) Bool.true;
mt331 := (Eq Tree).refl (full n9);
mt331 :: Eq Tree (mirror (full n9)) (full n9);
ft332 := (Eq Bool).refl Bool.true;
ft332 :: Eq Bool (alltrue (full n11)) Bool.true;
mt332 := (Eq Tree).refl (full n7);
mt332 :: Eq Tree (mirror (full n7)) (full n7);
ft333 := (Eq Bool).refl Bool.true;
ft333 :: Eq Bool (alltrue (full n10)) Bool.true;
mt333 := (Eq Tree).refl (full n10);
mt333 :: Eq Tree (mirror (full n10)) (full n10);
ft334 := (Eq Bool).refl Bool.true;
ft334 :: Eq Bool (alltrue (full n9)) Bool.true;
mt334 := (Eq Tree).refl (full n8);
mt334 :: Eq Tree (mirror (full n8)) (full n8);
ft335 := (Eq Bool).refl Bool.true;
ft335 :: Eq Bool (alltrue (full n8)) Bool.true;
mt335 := (Eq Tree).refl (full n6);
mt335 :: Eq Tree (mirror (full n6)) (full n6);
ft336 := (Eq Bool).refl Bool.true;
ft336 :: Eq Bool (alltrue (full n7)) Bool.true;
mt336 := (Eq Tree).refl (full n9);
mt336 :: Eq Tree (mirror (full n9)) (full n9);
ft337 := (Eq Bool).refl Bool.true;
ft337 :: Eq Bool (alltrue (full n12)) Bool.true;
mt337 := (Eq Tree).refl (full n7);
mt337 :: Eq Tree (mirror (full n7)) (full n7);
ft338 := (Eq Bool).refl Bool.true;
ft338 :: Eq Bool (alltrue (full n11)) Bool.true;
mt338 := (Eq Tree).refl (full n10);
mt338 :: Eq Tree (mirror (full n10)) (full n10);
ft339 := (Eq Bool).refl Bool.true;
ft339 :: Eq Bool (alltrue (full n10)) Bool.true;
mt339 := (Eq Tree).refl (full n8);
mt339 :: Eq Tree (mirror (full n8)) (full n8);
ft340 := (Eq Bool).refl Bool.true;
ft340 :: Eq Bool (alltrue (full n9)) Bool.true;
mt340 := (Eq Tree).refl (full n6);
mt340 :: Eq Tree (mirror (full n6)) (full n6);
ft341 := (Eq Bool).refl Bool.true;
ft341 :: Eq Bool (alltrue (full n8)) Bool.true;
mt341 := (Eq Tree).refl (full n9);
mt341 :: Eq Tree (mirror (full n9)) (full n9);
ft342 := (Eq Bool).refl Bool.true;
ft342 :: Eq Bool (alltrue (full n7)) Bool.true;
mt342 := (Eq Tree).refl (full n7);
mt342 :: Eq Tree (mirror (full n7)) (full n7);
ft343 := (Eq Bool).refl Bool.true;
ft343 :: Eq Bool (alltrue (full n12)) Bool.true;
mt343 := (Eq Tree).refl (full n10);
mt343 :: Eq Tree (mirror (full n10)) (full n10);
ft344 := (Eq Bool).refl Bool.true;
ft344 :: Eq Bool (alltrue (full n11)) Bool.true;
mt344 := (Eq Tree).refl (full n8);
mt344 :: Eq Tree (mirror (full n8)) (full n8);
ft345 := (Eq Bool).refl Bool.true;
ft345 :: Eq Bool (alltrue (full n10)) Bool.true;
mt345 := (Eq Tree).refl (full n6);
mt345 :: Eq Tree (mirror (full n6)) (full n6);
ft346 := (Eq Bool).refl Bool.true;
ft346 :: Eq Bool (alltrue (full n9)) Bool.true;
mt346 := (Eq Tree).refl (full n9);
mt346 :: Eq Tree (mirror (full n9)) (full n9);
ft347 := (Eq Bool).refl Bool.true;
ft347 :: Eq Bool (alltrue (full n8)) Bool.true;
mt347 := (Eq Tree).refl (full n7);
mt347 :: Eq Tree (mirror (full n7)) (full n7);
ft348 := (Eq Bool).refl Bool.true;
ft348 :: Eq Bool (alltrue (full n7)) Bool.true;
mt348 := (Eq Tree).refl (full n10);
mt348 :: Eq Tree (mirror (full n10)) (full n10);
ft349 := (Eq Bool).refl Bool.true;
ft349 :: Eq Bool (alltrue (full n12)) Bool.true;
mt349 := (Eq Tree).refl (full n8);
mt349 :: Eq Tree (mirror (full n8)) (full n8);
ft350 := (Eq Bool).refl Bool.true;
ft350 :: Eq Bool (alltrue (full n11)) Bool.true;
mt350 := (Eq Tree).refl (full n6);
mt350 :: Eq Tree (mirror (full n6)) (full n6);
ft351 := (Eq Bool).refl Bool.true;
ft351 :: Eq Bool (alltrue (full n10)) Bool.true;
mt351 := (Eq Tree).refl (full n9);
mt351 :: Eq Tree (mirror (full n9)) (full n9);
ft352 := (Eq Bool).refl Bool.true;
ft352 :: Eq Bool (alltrue (full n9)) Bool.true;
mt352 := (Eq Tree).refl (full n7);
mt352 :: Eq Tree (mirror (full n7)) (full n7);
ft353 := (Eq Bool).refl Bool.true;
ft353 :: Eq Bool (alltrue (full n8)) Bool.true;
mt353 := (Eq Tree).refl (full n10);
mt353 :: Eq Tree (mirror (full n10)) (full n10);
ft354 := (Eq Bool).refl Bool.true;
ft354 :: Eq Bool (alltrue (full n7)) Bool.true;
mt354 := (Eq Tree).refl (full n8);
mt354 :: Eq Tree (mirror (full n8)) (full n8);
ft355 := (Eq Bool).refl Bool.true;
ft355 :: Eq Bool (alltrue (full n12)) Bool.true;
mt355 := (Eq Tree).refl (full n6);
mt355 :: Eq Tree (mirror (full n6)) (full n6);
ft356 := (Eq Bool).refl Bool.true;
ft356 :: Eq Bool (alltrue (full n11)) Bool.true;
mt356 := (Eq Tree).refl (full n9);
mt356 :: Eq Tree (mirror (full n9)) (full n9);
ft357 := (Eq Bool).refl Bool.true;
ft357 :: Eq Bool (alltrue (full n10)) Bool.true;
mt357 := (Eq Tree).refl (full n7);
mt357 :: Eq Tree (mirror (full n7)) (full n7);
ft358 := (Eq Bool).refl Bool.true;
ft358 :: Eq Bool (alltrue (full n9)) Bool.true;
mt358 := (Eq Tree).refl (full n10);
mt358 :: Eq Tree (mirror (full n10)) (full n10);
ft359 := (Eq Bool).refl Bool.true;
ft359 :: Eq Bool (alltrue (full n8)) Bool.true;
mt359 := (Eq Tree).refl (full n8);
mt359 :: Eq Tree (mirror (full n8)) (full n8);
ft360 := (Eq Bool).refl Bool.true;
ft360 :: Eq Bool (alltrue (full n7)) Bool.true;
mt360 := (Eq Tree).refl (full n6);
mt360 :: Eq Tree (mirror (full n6)) (full n6);
ft361 := (Eq Bool).refl Bool.true;
ft361 :: Eq Bool (alltrue (full n12)) Bool.true;
mt361 := (Eq Tree).refl (full n9);
mt361 :: Eq Tree (mirror (full n9)) (full n9);
ft362 := (Eq Bool).refl Bool.true;
ft362 :: Eq Bool (alltrue (full n11)) Bool.true;
mt362 := (Eq Tree).refl (full n7);
mt362 :: Eq Tree (mirror (full n7)) (full n7);
ft363 := (Eq Bool).refl Bool.true;
ft363 :: Eq Bool (alltrue (full n10)) Bool.true;
mt363 := (Eq Tree).refl (full n10);
mt363 :: Eq Tree (mirror (full n10)) (full n10);
ft364 := (Eq Bool).refl Bool.true;
ft364 :: Eq Bool (alltrue (full n9)) Bool.true;
mt364 := (Eq Tree).refl (full n8);
mt364 :: Eq Tree (mirror (full n8)) (full n8);
ft365 := (Eq Bool).refl Bool.true;
ft365 :: Eq Bool (alltrue (full n8)) Bool.true;
mt365 := (Eq Tree).refl (full n6);
mt365 :: Eq Tree (mirror (full n6)) (full n6);
ft366 := (Eq Bool).refl Bool.true;
ft366 :: Eq Bool (alltrue (full n7)) Bool.true;
mt366 := (Eq Tree).refl (full n9);
mt366 :: Eq Tree (mirror (full n9)) (full n9);
ft367 := (Eq Bool).refl Bool.true;
ft367 :: Eq Bool (alltrue (full n12)) Bool.true;
mt367 := (Eq Tree).refl (full n7);
mt367 :: Eq Tree (mirror (full n7)) (full n7);
ft368 := (Eq Bool).refl Bool.true;
ft368 :: Eq Bool (alltrue (full n11)) Bool.true;
mt368 := (Eq Tree).refl (full n10);
mt368 :: Eq Tree (mirror (full n10)) (full n10);
ft369 := (Eq Bool).refl Bool.true;
ft369 :: Eq Bool (alltrue (full n10)) Bool.true;
mt369 := (Eq Tree).refl (full n8);
mt369 :: Eq Tree (mirror (full n8)) (full n8);
ft370 := (Eq Bool).refl Bool.true;
ft370 :: Eq Bool (alltrue (full n9)) Bool.true;
mt370 := (Eq Tree).refl (full n6);
mt370 :: Eq Tree (mirror (full n6)) (full n6);
ft371 := (Eq Bool).refl Bool.true;
ft371 :: Eq Bool (alltrue (full n8)) Bool.true;
mt371 := (Eq Tree).refl (full n9);
mt371 :: Eq Tree (mirror (full n9)) (full n9);
ft372 := (Eq Bool).refl Bool.true;
ft372 :: Eq Bool (alltrue (full n7)) Bool.true;
mt372 := (Eq Tree).refl (full n7);
mt372 :: Eq Tree (mirror (full n7)) (full n7);
ft373 := (Eq Bool).refl Bool.true;
ft373 :: Eq Bool (alltrue (full n12)) Bool.true;
mt373 := (Eq Tree).refl (full n10);
mt373 :: Eq Tree (mirror (full n10)) (full n10);
ft374 := (Eq Bool).refl Bool.true;
ft374 :: Eq Bool (alltrue (full n11)) Bool.true;
mt374 := (Eq Tree).refl (full n8);
mt374 :: Eq Tree (mirror (full n8)) (full n8);
ft375 := (Eq Bool).refl Bool.true;
ft375 :: Eq Bool (alltrue (full n10)) Bool.true;
mt375 := (Eq Tree).refl (full n6);
mt375 :: Eq Tree (mirror (full n6)) (full n6);
ft376 := (Eq Bool).refl Bool.true;
ft376 :: Eq Bool (alltrue (full n9)) Bool.true;
mt376 := (Eq Tree).refl (full n9);
mt376 :: Eq Tree (mirror (full n9)) (full n9);
ft377 := (Eq Bool).refl Bool.true;
ft377 :: Eq Bool (alltrue (full n8)) Bool.true;
mt377 := (Eq Tree).refl (full n7);
mt377 :: Eq Tree (mirror (full n7)) (full n7);
ft378 := (Eq Bool).refl Bool.true;
ft378 :: Eq Bool (alltrue (full n7)) Bool.true;
mt378 := (Eq Tree).refl (full n10);
mt378 :: Eq Tree (mirror (full n10)) (full n10);
ft379 := (Eq Bool).refl Bool.true;
ft379 :: Eq Bool (alltrue (full n12)) Bool.true;
mt379 := (Eq Tree).refl (full n8);
mt379 :: Eq Tree (mirror (full n8)) (full n8);
ft380 := (Eq Bool).refl Bool.true;
ft380 :: Eq Bool (alltrue (full n11)) Bool.true;
mt380 := (Eq Tree).refl (full n6);
mt380 :: Eq Tree (mirror (full n6)) (full n6);
ft381 := (Eq Bool).refl Bool.true;
ft381 :: Eq Bool (alltrue (full n10)) Bool.true;
mt381 := (Eq Tree).refl (full n9);
mt381 :: Eq Tree (mirror (full n9)) (full n9);
ft382 := (Eq Bool).refl Bool.true;
ft382 :: Eq Bool (alltrue (full n9)) Bool.true;
mt382 := (Eq Tree).refl (full n7);
mt382 :: Eq Tree (mirror (full n7)) (full n7);
ft383 := (Eq Bool).refl Bool.true;
ft383 :: Eq Bool (alltrue (full n8)) Bool.true;
mt383 := (Eq Tree).refl (full n10);
mt383 :: Eq Tree (mirror (full n10)) (full n10);
ft384 := (Eq Bool).refl Bool.true;
ft384 :: Eq Bool (alltrue (full n7)) Bool.true;
mt384 := (Eq Tree).refl (full n8);
mt384 :: Eq Tree (mirror (full n8)) (full n8);
ft385 := (Eq Bool).refl Bool.true;
ft385 :: Eq Bool (alltrue (full n12)) Bool.true;
mt385 := (Eq Tree).refl (full n6);
mt385 :: Eq Tree (mirror (full n6)) (full n6);
ft386 := (Eq Bool).refl Bool.true;
ft386 :: Eq Bool (alltrue (full n11)) Bool.true;
mt386 := (Eq Tree).refl (full n9);
mt386 :: Eq Tree (mirror (full n9)) (full n9);
ft387 := (Eq Bool).refl Bool.true;
ft387 :: Eq Bool (alltrue (full n10)) Bool.true;
mt387 := (Eq Tree).refl (full n7);
mt387 :: Eq Tree (mirror (full n7)) (full n7);
ft388 := (Eq Bool).refl Bool.true;
ft388 :: Eq Bool (alltrue (full n9)) Bool.true;
mt388 := (Eq Tree).refl (full n10);
mt388 :: Eq Tree (mirror (full n10)) (full n10);
ft389 := (Eq Bool).refl Bool.true;
ft389 :: Eq Bool (alltrue (full n8)) Bool.true;
mt389 := (Eq Tree).refl (full n8);
mt389 :: Eq Tree (mirror (full n8)) (full n8);
ft390 := (Eq Bool).refl Bool.true;
ft390 :: Eq Bool (alltrue (full n7)) Bool.true;
mt390 := (Eq Tree).refl (full n6);
mt390 :: Eq Tree (mirror (full n6)) (full n6);
ft391 := (Eq Bool).refl Bool.true;
ft391 :: Eq Bool (alltrue (full n12)) Bool.true;
mt391 := (Eq Tree).refl (full n9);
mt391 :: Eq Tree (mirror (full n9)) (full n9);
ft392 := (Eq Bool).refl Bool.true;
ft392 :: Eq Bool (alltrue (full n11)) Bool.true;
mt392 := (Eq Tree).refl (full n7);
mt392 :: Eq Tree (mirror (full n7)) (full n7);
ft393 := (Eq Bool).refl Bool.true;
ft393 :: Eq Bool (alltrue (full n10)) Bool.true;
mt393 := (Eq Tree).refl (full n10);
mt393 :: Eq Tree (mirror (full n10)) (full n10);
ft394 := (Eq Bool).refl Bool.true;
ft394 :: Eq Bool (alltrue (full n9)) Bool.true;
mt394 := (Eq Tree).refl (full n8);
mt394 :: Eq Tree (mirror (full n8)) (full n8);
ft395 := (Eq Bool).refl Bool.true;
ft395 :: Eq Bool (alltrue (full n8)) Bool.true;
mt395 := (Eq Tree).refl (full n6);
mt395 :: Eq Tree (mirror (full n6)) (full n6);
ft396 := (Eq Bool).refl Bool.true;
ft396 :: Eq Bool (alltrue (full n7)) Bool.true;
mt396 := (Eq Tree).refl (full n9);
mt396 :: Eq Tree (mirror (full n9)) (full n9);
ft397 := (Eq Bool).refl Bool.true;
ft397 :: Eq Bool (alltrue (full n12)) Bool.true;
mt397 := (Eq Tree).refl (full n7);
mt397 :: Eq Tree (mirror (full n7)) (full n7);
ft398 := (Eq Bool).refl Bool.true;
ft398 :: Eq Bool (alltrue (full n11)) Bool.true;
mt398 := (Eq Tree).refl (full n10);
mt398 :: Eq Tree (mirror (full n10)) (full n10);
ft399 := (Eq Bool).refl Bool.true;
ft399 :: Eq Bool (alltrue (full n10)) Bool.true;
mt399 := (Eq Tree).refl (full n8);
mt399 :: Eq Tree (mirror (full n8)) (full n8);
