// Concrete computational equalities, not universal tree theorems.
Nat := @{zero:*; succ:*->*;};
Bool := @{true:*; false:*;};
Tree := @{leaf:*; node:*->*->*;};
Eq := \A:@ => @\left:A => @\right:A => {refl:(x:A)->* x x;};
and := \a:Bool => \b:Bool => a @true => b @false => Bool.false;
full := \n:Nat => n @zero => Tree.leaf @succ p => Tree.node *p *p;
full :: Nat->Tree;
mirror := \t:Tree => t @leaf => Tree.leaf @node l r => Tree.node *r *l;
mirror :: Tree->Tree;
alltrue := \t:Tree => t @leaf => Bool.true @node l r => and *l *r;
alltrue :: Tree->Bool;
n0 := Nat.zero;
n1 := Nat.succ n0;
n2 := Nat.succ n1;
n3 := Nat.succ n2;
n4 := Nat.succ n3;
n5 := Nat.succ n4;
n6 := Nat.succ n5;
n7 := Nat.succ n6;
n8 := Nat.succ n7;
n9 := Nat.succ n8;
n10 := Nat.succ n9;
n11 := Nat.succ n10;
n12 := Nat.succ n11;
n13 := Nat.succ n12;
ft0 := (Eq Bool).refl Bool.true;
ft0 :: Eq Bool (alltrue (full n7)) Bool.true;
mt0 := (Eq Tree).refl (full n6);
mt0 :: Eq Tree (mirror (full n6)) (full n6);
ft1 := (Eq Bool).refl Bool.true;
ft1 :: Eq Bool (alltrue (full n12)) Bool.true;
mt1 := (Eq Tree).refl (full n9);
mt1 :: Eq Tree (mirror (full n9)) (full n9);
ft2 := (Eq Bool).refl Bool.true;
ft2 :: Eq Bool (alltrue (full n11)) Bool.true;
mt2 := (Eq Tree).refl (full n7);
mt2 :: Eq Tree (mirror (full n7)) (full n7);
ft3 := (Eq Bool).refl Bool.true;
ft3 :: Eq Bool (alltrue (full n10)) Bool.true;
mt3 := (Eq Tree).refl (full n10);
mt3 :: Eq Tree (mirror (full n10)) (full n10);
ft4 := (Eq Bool).refl Bool.true;
ft4 :: Eq Bool (alltrue (full n9)) Bool.true;
mt4 := (Eq Tree).refl (full n8);
mt4 :: Eq Tree (mirror (full n8)) (full n8);
ft5 := (Eq Bool).refl Bool.true;
ft5 :: Eq Bool (alltrue (full n8)) Bool.true;
mt5 := (Eq Tree).refl (full n6);
mt5 :: Eq Tree (mirror (full n6)) (full n6);
ft6 := (Eq Bool).refl Bool.true;
ft6 :: Eq Bool (alltrue (full n7)) Bool.true;
mt6 := (Eq Tree).refl (full n9);
mt6 :: Eq Tree (mirror (full n9)) (full n9);
ft7 := (Eq Bool).refl Bool.true;
ft7 :: Eq Bool (alltrue (full n12)) Bool.true;
mt7 := (Eq Tree).refl (full n7);
mt7 :: Eq Tree (mirror (full n7)) (full n7);
ft8 := (Eq Bool).refl Bool.true;
ft8 :: Eq Bool (alltrue (full n11)) Bool.true;
mt8 := (Eq Tree).refl (full n10);
mt8 :: Eq Tree (mirror (full n10)) (full n10);
ft9 := (Eq Bool).refl Bool.true;
ft9 :: Eq Bool (alltrue (full n10)) Bool.true;
mt9 := (Eq Tree).refl (full n8);
mt9 :: Eq Tree (mirror (full n8)) (full n8);
ft10 := (Eq Bool).refl Bool.true;
ft10 :: Eq Bool (alltrue (full n9)) Bool.true;
mt10 := (Eq Tree).refl (full n6);
mt10 :: Eq Tree (mirror (full n6)) (full n6);
ft11 := (Eq Bool).refl Bool.true;
ft11 :: Eq Bool (alltrue (full n8)) Bool.true;
mt11 := (Eq Tree).refl (full n9);
mt11 :: Eq Tree (mirror (full n9)) (full n9);
ft12 := (Eq Bool).refl Bool.true;
ft12 :: Eq Bool (alltrue (full n7)) Bool.true;
mt12 := (Eq Tree).refl (full n7);
mt12 :: Eq Tree (mirror (full n7)) (full n7);
ft13 := (Eq Bool).refl Bool.true;
ft13 :: Eq Bool (alltrue (full n12)) Bool.true;
mt13 := (Eq Tree).refl (full n10);
mt13 :: Eq Tree (mirror (full n10)) (full n10);
ft14 := (Eq Bool).refl Bool.true;
ft14 :: Eq Bool (alltrue (full n11)) Bool.true;
mt14 := (Eq Tree).refl (full n8);
mt14 :: Eq Tree (mirror (full n8)) (full n8);
ft15 := (Eq Bool).refl Bool.true;
ft15 :: Eq Bool (alltrue (full n10)) Bool.true;
mt15 := (Eq Tree).refl (full n6);
mt15 :: Eq Tree (mirror (full n6)) (full n6);
ft16 := (Eq Bool).refl Bool.true;
ft16 :: Eq Bool (alltrue (full n9)) Bool.true;
mt16 := (Eq Tree).refl (full n9);
mt16 :: Eq Tree (mirror (full n9)) (full n9);
ft17 := (Eq Bool).refl Bool.true;
ft17 :: Eq Bool (alltrue (full n8)) Bool.true;
mt17 := (Eq Tree).refl (full n7);
mt17 :: Eq Tree (mirror (full n7)) (full n7);
ft18 := (Eq Bool).refl Bool.true;
ft18 :: Eq Bool (alltrue (full n7)) Bool.true;
mt18 := (Eq Tree).refl (full n10);
mt18 :: Eq Tree (mirror (full n10)) (full n10);
ft19 := (Eq Bool).refl Bool.true;
ft19 :: Eq Bool (alltrue (full n12)) Bool.true;
mt19 := (Eq Tree).refl (full n8);
mt19 :: Eq Tree (mirror (full n8)) (full n8);
ft20 := (Eq Bool).refl Bool.true;
ft20 :: Eq Bool (alltrue (full n11)) Bool.true;
mt20 := (Eq Tree).refl (full n6);
mt20 :: Eq Tree (mirror (full n6)) (full n6);
ft21 := (Eq Bool).refl Bool.true;
ft21 :: Eq Bool (alltrue (full n10)) Bool.true;
mt21 := (Eq Tree).refl (full n9);
mt21 :: Eq Tree (mirror (full n9)) (full n9);
ft22 := (Eq Bool).refl Bool.true;
ft22 :: Eq Bool (alltrue (full n9)) Bool.true;
mt22 := (Eq Tree).refl (full n7);
mt22 :: Eq Tree (mirror (full n7)) (full n7);
ft23 := (Eq Bool).refl Bool.true;
ft23 :: Eq Bool (alltrue (full n8)) Bool.true;
mt23 := (Eq Tree).refl (full n10);
mt23 :: Eq Tree (mirror (full n10)) (full n10);
ft24 := (Eq Bool).refl Bool.true;
ft24 :: Eq Bool (alltrue (full n7)) Bool.true;
mt24 := (Eq Tree).refl (full n8);
mt24 :: Eq Tree (mirror (full n8)) (full n8);
ft25 := (Eq Bool).refl Bool.true;
ft25 :: Eq Bool (alltrue (full n12)) Bool.true;
mt25 := (Eq Tree).refl (full n6);
mt25 :: Eq Tree (mirror (full n6)) (full n6);
ft26 := (Eq Bool).refl Bool.true;
ft26 :: Eq Bool (alltrue (full n11)) Bool.true;
mt26 := (Eq Tree).refl (full n9);
mt26 :: Eq Tree (mirror (full n9)) (full n9);
ft27 := (Eq Bool).refl Bool.true;
ft27 :: Eq Bool (alltrue (full n10)) Bool.true;
mt27 := (Eq Tree).refl (full n7);
mt27 :: Eq Tree (mirror (full n7)) (full n7);
ft28 := (Eq Bool).refl Bool.true;
ft28 :: Eq Bool (alltrue (full n9)) Bool.true;
mt28 := (Eq Tree).refl (full n10);
mt28 :: Eq Tree (mirror (full n10)) (full n10);
ft29 := (Eq Bool).refl Bool.true;
ft29 :: Eq Bool (alltrue (full n8)) Bool.true;
mt29 := (Eq Tree).refl (full n8);
mt29 :: Eq Tree (mirror (full n8)) (full n8);
ft30 := (Eq Bool).refl Bool.true;
ft30 :: Eq Bool (alltrue (full n7)) Bool.true;
mt30 := (Eq Tree).refl (full n6);
mt30 :: Eq Tree (mirror (full n6)) (full n6);
ft31 := (Eq Bool).refl Bool.true;
ft31 :: Eq Bool (alltrue (full n12)) Bool.true;
mt31 := (Eq Tree).refl (full n9);
mt31 :: Eq Tree (mirror (full n9)) (full n9);
ft32 := (Eq Bool).refl Bool.true;
ft32 :: Eq Bool (alltrue (full n11)) Bool.true;
mt32 := (Eq Tree).refl (full n7);
mt32 :: Eq Tree (mirror (full n7)) (full n7);
ft33 := (Eq Bool).refl Bool.true;
ft33 :: Eq Bool (alltrue (full n10)) Bool.true;
mt33 := (Eq Tree).refl (full n10);
mt33 :: Eq Tree (mirror (full n10)) (full n10);
ft34 := (Eq Bool).refl Bool.true;
ft34 :: Eq Bool (alltrue (full n9)) Bool.true;
mt34 := (Eq Tree).refl (full n8);
mt34 :: Eq Tree (mirror (full n8)) (full n8);
ft35 := (Eq Bool).refl Bool.true;
ft35 :: Eq Bool (alltrue (full n8)) Bool.true;
mt35 := (Eq Tree).refl (full n6);
mt35 :: Eq Tree (mirror (full n6)) (full n6);
ft36 := (Eq Bool).refl Bool.true;
ft36 :: Eq Bool (alltrue (full n7)) Bool.true;
mt36 := (Eq Tree).refl (full n9);
mt36 :: Eq Tree (mirror (full n9)) (full n9);
ft37 := (Eq Bool).refl Bool.true;
ft37 :: Eq Bool (alltrue (full n12)) Bool.true;
mt37 := (Eq Tree).refl (full n7);
mt37 :: Eq Tree (mirror (full n7)) (full n7);
ft38 := (Eq Bool).refl Bool.true;
ft38 :: Eq Bool (alltrue (full n11)) Bool.true;
mt38 := (Eq Tree).refl (full n10);
mt38 :: Eq Tree (mirror (full n10)) (full n10);
ft39 := (Eq Bool).refl Bool.true;
ft39 :: Eq Bool (alltrue (full n10)) Bool.true;
mt39 := (Eq Tree).refl (full n8);
mt39 :: Eq Tree (mirror (full n8)) (full n8);
ft40 := (Eq Bool).refl Bool.true;
ft40 :: Eq Bool (alltrue (full n9)) Bool.true;
mt40 := (Eq Tree).refl (full n6);
mt40 :: Eq Tree (mirror (full n6)) (full n6);
ft41 := (Eq Bool).refl Bool.true;
ft41 :: Eq Bool (alltrue (full n8)) Bool.true;
mt41 := (Eq Tree).refl (full n9);
mt41 :: Eq Tree (mirror (full n9)) (full n9);
ft42 := (Eq Bool).refl Bool.true;
ft42 :: Eq Bool (alltrue (full n7)) Bool.true;
mt42 := (Eq Tree).refl (full n7);
mt42 :: Eq Tree (mirror (full n7)) (full n7);
ft43 := (Eq Bool).refl Bool.true;
ft43 :: Eq Bool (alltrue (full n12)) Bool.true;
mt43 := (Eq Tree).refl (full n10);
mt43 :: Eq Tree (mirror (full n10)) (full n10);
ft44 := (Eq Bool).refl Bool.true;
ft44 :: Eq Bool (alltrue (full n11)) Bool.true;
mt44 := (Eq Tree).refl (full n8);
mt44 :: Eq Tree (mirror (full n8)) (full n8);
ft45 := (Eq Bool).refl Bool.true;
ft45 :: Eq Bool (alltrue (full n10)) Bool.true;
mt45 := (Eq Tree).refl (full n6);
mt45 :: Eq Tree (mirror (full n6)) (full n6);
ft46 := (Eq Bool).refl Bool.true;
ft46 :: Eq Bool (alltrue (full n9)) Bool.true;
mt46 := (Eq Tree).refl (full n9);
mt46 :: Eq Tree (mirror (full n9)) (full n9);
ft47 := (Eq Bool).refl Bool.true;
ft47 :: Eq Bool (alltrue (full n8)) Bool.true;
mt47 := (Eq Tree).refl (full n7);
mt47 :: Eq Tree (mirror (full n7)) (full n7);
ft48 := (Eq Bool).refl Bool.true;
ft48 :: Eq Bool (alltrue (full n7)) Bool.true;
mt48 := (Eq Tree).refl (full n10);
mt48 :: Eq Tree (mirror (full n10)) (full n10);
ft49 := (Eq Bool).refl Bool.true;
ft49 :: Eq Bool (alltrue (full n12)) Bool.true;
mt49 := (Eq Tree).refl (full n8);
mt49 :: Eq Tree (mirror (full n8)) (full n8);
ft50 := (Eq Bool).refl Bool.true;
ft50 :: Eq Bool (alltrue (full n11)) Bool.true;
mt50 := (Eq Tree).refl (full n6);
mt50 :: Eq Tree (mirror (full n6)) (full n6);
ft51 := (Eq Bool).refl Bool.true;
ft51 :: Eq Bool (alltrue (full n10)) Bool.true;
mt51 := (Eq Tree).refl (full n9);
mt51 :: Eq Tree (mirror (full n9)) (full n9);
ft52 := (Eq Bool).refl Bool.true;
ft52 :: Eq Bool (alltrue (full n9)) Bool.true;
mt52 := (Eq Tree).refl (full n7);
mt52 :: Eq Tree (mirror (full n7)) (full n7);
ft53 := (Eq Bool).refl Bool.true;
ft53 :: Eq Bool (alltrue (full n8)) Bool.true;
mt53 := (Eq Tree).refl (full n10);
mt53 :: Eq Tree (mirror (full n10)) (full n10);
ft54 := (Eq Bool).refl Bool.true;
ft54 :: Eq Bool (alltrue (full n7)) Bool.true;
mt54 := (Eq Tree).refl (full n8);
mt54 :: Eq Tree (mirror (full n8)) (full n8);
ft55 := (Eq Bool).refl Bool.true;
ft55 :: Eq Bool (alltrue (full n12)) Bool.true;
mt55 := (Eq Tree).refl (full n6);
mt55 :: Eq Tree (mirror (full n6)) (full n6);
ft56 := (Eq Bool).refl Bool.true;
ft56 :: Eq Bool (alltrue (full n11)) Bool.true;
mt56 := (Eq Tree).refl (full n9);
mt56 :: Eq Tree (mirror (full n9)) (full n9);
ft57 := (Eq Bool).refl Bool.true;
ft57 :: Eq Bool (alltrue (full n10)) Bool.true;
mt57 := (Eq Tree).refl (full n7);
mt57 :: Eq Tree (mirror (full n7)) (full n7);
ft58 := (Eq Bool).refl Bool.true;
ft58 :: Eq Bool (alltrue (full n9)) Bool.true;
mt58 := (Eq Tree).refl (full n10);
mt58 :: Eq Tree (mirror (full n10)) (full n10);
ft59 := (Eq Bool).refl Bool.true;
ft59 :: Eq Bool (alltrue (full n8)) Bool.true;
mt59 := (Eq Tree).refl (full n8);
mt59 :: Eq Tree (mirror (full n8)) (full n8);
ft60 := (Eq Bool).refl Bool.true;
ft60 :: Eq Bool (alltrue (full n7)) Bool.true;
mt60 := (Eq Tree).refl (full n6);
mt60 :: Eq Tree (mirror (full n6)) (full n6);
ft61 := (Eq Bool).refl Bool.true;
ft61 :: Eq Bool (alltrue (full n12)) Bool.true;
mt61 := (Eq Tree).refl (full n9);
mt61 :: Eq Tree (mirror (full n9)) (full n9);
ft62 := (Eq Bool).refl Bool.true;
ft62 :: Eq Bool (alltrue (full n11)) Bool.true;
mt62 := (Eq Tree).refl (full n7);
mt62 :: Eq Tree (mirror (full n7)) (full n7);
ft63 := (Eq Bool).refl Bool.true;
ft63 :: Eq Bool (alltrue (full n10)) Bool.true;
mt63 := (Eq Tree).refl (full n10);
mt63 :: Eq Tree (mirror (full n10)) (full n10);
