// Concrete computational equalities, not universal tree theorems.
Nat := @{zero:*; succ:*->*;};
Bool := @{true:*; false:*;};
Tree := @{leaf:*; node:*->*->*;};
Eq := \A:@ => @\left:A => @\right:A => {refl:(x:A)->* x x;};
and := \a:Bool => \b:Bool => a @true => b @false => Bool.false;
full := \n:Nat => n @zero => Tree.leaf @succ p => Tree.node *p *p;
full :: Nat->Tree;
mirror := \t:Tree => t @leaf => Tree.leaf @node l r => Tree.node *r *l;
mirror :: Tree->Tree;
alltrue := \t:Tree => t @leaf => Bool.true @node l r => and *l *r;
alltrue :: Tree->Bool;
n0 := Nat.zero;
n1 := Nat.succ n0;
n2 := Nat.succ n1;
n3 := Nat.succ n2;
n4 := Nat.succ n3;
n5 := Nat.succ n4;
n6 := Nat.succ n5;
n7 := Nat.succ n6;
n8 := Nat.succ n7;
n9 := Nat.succ n8;
n10 := Nat.succ n9;
n11 := Nat.succ n10;
n12 := Nat.succ n11;
n13 := Nat.succ n12;
ft0 := (Eq Bool).refl Bool.true;
ft0 :: Eq Bool (alltrue (full n7)) Bool.true;
mt0 := (Eq Tree).refl (full n6);
mt0 :: Eq Tree (mirror (full n6)) (full n6);
ft1 := (Eq Bool).refl Bool.true;
ft1 :: Eq Bool (alltrue (full n12)) Bool.true;
mt1 := (Eq Tree).refl (full n9);
mt1 :: Eq Tree (mirror (full n9)) (full n9);
ft2 := (Eq Bool).refl Bool.true;
ft2 :: Eq Bool (alltrue (full n11)) Bool.true;
mt2 := (Eq Tree).refl (full n7);
mt2 :: Eq Tree (mirror (full n7)) (full n7);
ft3 := (Eq Bool).refl Bool.true;
ft3 :: Eq Bool (alltrue (full n10)) Bool.true;
mt3 := (Eq Tree).refl (full n10);
mt3 :: Eq Tree (mirror (full n10)) (full n10);
