#ifndef A_PROGRAM_PROTOTYPE_CORE_TERM_SCHEMA_H
#define A_PROGRAM_PROTOTYPE_CORE_TERM_SCHEMA_H

#include <stddef.h>
#include <stdint.h>

#include "a_program/core/term.h"

/* This schema describes stored payload fields. It does not define reduction,
 * typing, alpha-equivalence, or persistent byte order. */
enum prototype_term_field_kind {
	PROTOTYPE_TERM_FIELD_TERM_REQUIRED = 1,
	PROTOTYPE_TERM_FIELD_TERM_OPTIONAL = 2,
	PROTOTYPE_TERM_FIELD_BINDING = 3,
	PROTOTYPE_TERM_FIELD_IH_SCOPE = 4,
	PROTOTYPE_TERM_FIELD_CASE_SLICE = 5,
	PROTOTYPE_TERM_FIELD_FOLD_CLAUSE_SLICE = 6,
	PROTOTYPE_TERM_FIELD_TYPE_DECLARATION = 7,
	PROTOTYPE_TERM_FIELD_REPRESENTATION = 8,
	PROTOTYPE_TERM_FIELD_SYMBOL = 9,
	PROTOTYPE_TERM_FIELD_OPERATION = 10,
	PROTOTYPE_TERM_FIELD_UNIVERSE_LEVEL = 11,
	PROTOTYPE_TERM_FIELD_DIMENSION_OPERATOR = 12,
	PROTOTYPE_TERM_FIELD_SCALAR_U32 = 13,
	PROTOTYPE_TERM_FIELD_SCALAR_I32 = 14,
	PROTOTYPE_TERM_FIELD_SCALAR_I64 = 15
};

enum prototype_term_field_role {
	PROTOTYPE_TERM_FIELD_ROLE_INVALID = 0,
	PROTOTYPE_TERM_FIELD_ROLE_VAR_BINDING = 1,
	PROTOTYPE_TERM_FIELD_ROLE_CONSTRUCTOR_OWNER = 2,
	PROTOTYPE_TERM_FIELD_ROLE_CONSTRUCTOR_ORDINAL = 3,
	PROTOTYPE_TERM_FIELD_ROLE_APP_FUNCTION = 4,
	PROTOTYPE_TERM_FIELD_ROLE_APP_ARGUMENT = 5,
	PROTOTYPE_TERM_FIELD_ROLE_LAMBDA_BINDING = 6,
	PROTOTYPE_TERM_FIELD_ROLE_LAMBDA_BODY = 7,
	PROTOTYPE_TERM_FIELD_ROLE_PI_DOMAIN = 8,
	PROTOTYPE_TERM_FIELD_ROLE_PI_CODOMAIN_FAMILY = 9,
	PROTOTYPE_TERM_FIELD_ROLE_MATCH_SCRUTINEE = 10,
	PROTOTYPE_TERM_FIELD_ROLE_MATCH_FIRST_CASE = 11,
	PROTOTYPE_TERM_FIELD_ROLE_MATCH_CASE_COUNT = 12,
	PROTOTYPE_TERM_FIELD_ROLE_MATCH_IH_SCOPE = 13,
	PROTOTYPE_TERM_FIELD_ROLE_TYPE_FORMER_DECLARATION = 14,
	PROTOTYPE_TERM_FIELD_ROLE_TYPE_FORMER_REPRESENTATION = 15,
	PROTOTYPE_TERM_FIELD_ROLE_TYPE_FORMER_CONSTRUCTOR_COUNT = 16,
	PROTOTYPE_TERM_FIELD_ROLE_TYPE_DECLARATION_ID = 17,
	PROTOTYPE_TERM_FIELD_ROLE_TYPE_DECLARATION_NAMESPACE = 18,
	PROTOTYPE_TERM_FIELD_ROLE_TYPE_DECLARATION_NAME = 19,
	PROTOTYPE_TERM_FIELD_ROLE_TYPE_VIEW_ID = 20,
	PROTOTYPE_TERM_FIELD_ROLE_TYPE_VIEW_NAMESPACE = 21,
	PROTOTYPE_TERM_FIELD_ROLE_TYPE_VIEW_NAME = 22,
	PROTOTYPE_TERM_FIELD_ROLE_TYPE_VIEW_CORE = 23,
	PROTOTYPE_TERM_FIELD_ROLE_TYPE_VIEW_SOURCE = 24,
	PROTOTYPE_TERM_FIELD_ROLE_IH_SCOPE = 25,
	PROTOTYPE_TERM_FIELD_ROLE_IH_ARGUMENT = 26,
	PROTOTYPE_TERM_FIELD_ROLE_UNIVERSE_LEVEL = 27,
	PROTOTYPE_TERM_FIELD_ROLE_TEXT_SYMBOL = 28,
	PROTOTYPE_TERM_FIELD_ROLE_INT_LITERAL = 29,
	PROTOTYPE_TERM_FIELD_ROLE_EXTERNAL_NAMESPACE = 30,
	PROTOTYPE_TERM_FIELD_ROLE_EXTERNAL_NAME = 31,
	PROTOTYPE_TERM_FIELD_ROLE_PRIMITIVE_ID = 32,
	PROTOTYPE_TERM_FIELD_ROLE_PRIMITIVE_TYPE = 33,
	PROTOTYPE_TERM_FIELD_ROLE_EFFECT_OPERATION_ID = 34,
	PROTOTYPE_TERM_FIELD_ROLE_EFFECT_OPERATION_CLASSIFIER = 35,
	PROTOTYPE_TERM_FIELD_ROLE_EFFECT_ROW_BINDING = 36,
	PROTOTYPE_TERM_FIELD_ROLE_EFFECT_ROW_LEFT = 37,
	PROTOTYPE_TERM_FIELD_ROLE_EFFECT_ROW_RIGHT = 38,
	PROTOTYPE_TERM_FIELD_ROLE_EFFECT_ROW_FORALL_BINDING = 39,
	PROTOTYPE_TERM_FIELD_ROLE_EFFECT_ROW_FORALL_BODY = 40,
	PROTOTYPE_TERM_FIELD_ROLE_EFFECT_ROW_OPERATION_ID = 41,
	PROTOTYPE_TERM_FIELD_ROLE_EFFECT_ROW_LATENT = 42,
	PROTOTYPE_TERM_FIELD_ROLE_COMPUTATION_EFFECT_ROW = 43,
	PROTOTYPE_TERM_FIELD_ROLE_COMPUTATION_RESULT = 44,
	PROTOTYPE_TERM_FIELD_ROLE_COMPUTATION_TOTALITY = 45,
	PROTOTYPE_TERM_FIELD_ROLE_THUNK_TYPE_COMPUTATION = 46,
	PROTOTYPE_TERM_FIELD_ROLE_RETURN_VALUE = 47,
	PROTOTYPE_TERM_FIELD_ROLE_THUNK_COMPUTATION = 48,
	PROTOTYPE_TERM_FIELD_ROLE_FORCE_VALUE = 49,
	PROTOTYPE_TERM_FIELD_ROLE_REQUEST_OPERATION = 50,
	PROTOTYPE_TERM_FIELD_ROLE_REQUEST_ARGUMENT = 51,
	PROTOTYPE_TERM_FIELD_ROLE_REQUEST_CONTINUATION = 52,
	PROTOTYPE_TERM_FIELD_ROLE_FOLD_COMPUTATION = 53,
	PROTOTYPE_TERM_FIELD_ROLE_FOLD_RETURN_CLAUSE = 54,
	PROTOTYPE_TERM_FIELD_ROLE_FOLD_FIRST_CLAUSE = 55,
	PROTOTYPE_TERM_FIELD_ROLE_FOLD_CLAUSE_COUNT = 56,
	PROTOTYPE_TERM_FIELD_ROLE_DIMENSION_ACTION_SOURCE = 57,
	PROTOTYPE_TERM_FIELD_ROLE_DIMENSION_ACTION_OPERATOR = 58
};

struct prototype_term_field_value {
	int kind;
	int role;
	int child_role;
	union {
		uint32_t u32;
		int i32;
		int64_t i64;
	} as;
};

int prototype_term_schema_tag_known(int tag);
int prototype_term_schema_field_count(int tag, size_t* p_count);

int prototype_term_schema_field_at(
	const struct prototype_term* term,
	size_t field_index,
	struct prototype_term_field_value* p_value
);

int prototype_term_schema_field_write(
	struct prototype_term* term,
	size_t field_index,
	const struct prototype_term_field_value* value
);

int prototype_term_schema_fixed_child_count(
	const struct prototype_term* term,
	uint32_t* p_count
);

int prototype_term_schema_fixed_child_at(
	const struct prototype_term* term,
	uint32_t child_index,
	struct prototype_term_child* p_child
);

#endif
